### ISSUE TITLE
Crash when initializing cache

### ISSUE THREAD

**Issue by owenh** [jborg/attic#108]
I have received this error several times during cache initialization. It may be that it is happening after all the individual archives are successfully analyzed, but before the initialization finishes. However, I can not be sure because I can not get a list of archives without a working cache.

Thanks!

```sh
attic create --verbose --stats --do-not-cross-mountpoints \
    --exclude-caches --exclude-from excludes.txt \
    server:/srv/attic::name_$(date -u +"%Y%m%dT%H%M%SZ") ~
Initializing cache...
(successfully analyzed about 97 archives...)
```
```python
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/attic/remote.py", line 298, in get_many
    yield self.load_object(*self.index[key])
  File "hashindex.pyx", line 95, in attic.hashindex.NSIndex.__getitem__ (attic/hashindex.c:2315)
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/attic", line 3, in <module>
    main()
  File "/usr/lib/python3/dist-packages/attic/archiver.py", line 715, in main
    exit_code = archiver.run(sys.argv[1:])
  File "/usr/lib/python3/dist-packages/attic/archiver.py", line 705, in run
    return args.func(args)
  File "/usr/lib/python3/dist-packages/attic/archiver.py", line 100, in do_create
    cache = Cache(repository, key, manifest)
  File "/usr/lib/python3/dist-packages/attic/cache.py", line 33, in __init__
    self.sync()
  File "/usr/lib/python3/dist-packages/attic/cache.py", line 163, in sync
    for key, chunk in zip(archive[b'items'], repository.get_many(archive[b'items'])):
  File "/usr/lib/python3/dist-packages/attic/remote.py", line 302, in get_many
    self.store_object(key, data)
  File "/usr/lib/python3/dist-packages/attic/remote.py", line 288, in store_object
    self.index[key] = offset - len(data), len(data)
  File "hashindex.pyx", line 101, in attic.hashindex.NSIndex.__setitem__ (attic/hashindex.c:2424)
OverflowError: value too large to convert to int
```

**Comment by ThomasWaldmann** [comment]
can you reproduce this with 0.14?

**Comment by owenh** [comment]
Sorry for the delay!

Because my local cache became inconsistent with the remote repository and cache initialization was failing, I eventually had to give up and replace my remote repository. This is related to [issue 107](https://github.com/jborg/attic/issues/107). Since then, I have been careful to keep my local cache consistent and attic has not needed to do cache initialization again.

But I will try to do some more testing when I have time!

Platform is Debian GNU/Linux amd64. I am not sure what you mean by processor type, but it is an Intel Core 2 Duo. Is there any additional information that would be helpful?

**Comment by jborg** [comment]
Ok, I'm closing this now. Open a new issue if you're able to reproduce this again.
