### ISSUE TITLE
cifs destination exception: listxattr failed

### ISSUE THREAD

**Issue by jbd** [jborg/attic#120]
Hi,

I'm using Attic 0.13 from Debian Jessie and I've got a problem with my CIFS repository. It was working a few days ago, and of course, I'm absolutely unable to provide you what changed (did a bunch of apt-get upgrade)

My backup script looks like that :

```
REPOSITORY=/mnt/cifs
ATTIC_PASSPHRASE="XXXX"

export ATTIC_PASSPHRASE

# excluded directories
attic create --stats                            \
    $REPOSITORY::`date +%Y-%m-%d`               \
    /data                                       \
    --exclude /data/home/*/.cache               \
    --exclude /data/volatile                    \
    --exclude '*.pyc'                           \
    --exclude '*.o'                             \
```

And I've got this traceback :

```
Traceback (most recent call last):
  File "/usr/bin/attic", line 3, in <module>
    main()
  File "/usr/lib/python3/dist-packages/attic/archiver.py", line 715, in main
    exit_code = archiver.run(sys.argv[1:])
  File "/usr/lib/python3/dist-packages/attic/archiver.py", line 705, in run
    return args.func(args)
  File "/usr/lib/python3/dist-packages/attic/archiver.py", line 128, in do_create
    self._process(archive, cache, args.excludes, args.exclude_caches, skip_inodes, path, restrict_dev)
  File "/usr/lib/python3/dist-packages/attic/archiver.py", line 177, in _process
    os.path.join(path, filename), restrict_dev)
  File "/usr/lib/python3/dist-packages/attic/archiver.py", line 169, in _process
    archive.process_item(path, st)
  File "/usr/lib/python3/dist-packages/attic/archive.py", line 361, in process_item
    item.update(self.stat_attrs(st, path))
  File "/usr/lib/python3/dist-packages/attic/archive.py", line 351, in stat_attrs
    xattrs = xattr.get_all(path, follow_symlinks=False)
  File "/usr/lib/python3/dist-packages/attic/xattr.py", line 25, in get_all
    for name in listxattr(path, follow_symlinks=follow_symlinks))
  File "/usr/lib/python3/dist-packages/attic/xattr.py", line 68, in listxattr
    raise Exception('listxattr failed')
```

I've instrumented the code to show the error code, which "22" (Invalid argument). Any idea what could cause it ?

**Comment by ThomasWaldmann** [comment]
Do I understand correctly:
CIFS is only the target fs where your repository is?
But everything below /data is a Linux filesystem that should support extended attributes?
Because it looks like it is stumbling over sth at the source, not at the target.

**Comment by ThomasWaldmann** [comment]
close this due to inactivity?

**Comment by pepa65** [comment]
Came across this issue after my borg (1.0.6-2~ubuntu14.04.1~ppa1) failed just now. The sequence of traceback is almost exactly the same, except this is from xfs to xfs, on Ubuntu 14.04 trusty. Of my five directories (each a separate archive, same repo) only one worked. Yesterday all five worked.
Example failure:
``` 
borg create -v --show-rc --stats -C lz4 /data/store/borg::Public-20160810 /data/Public
Enter passphrase for key /data/store/borg:
Local Exception.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1609, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1546, in run
    return args.func(args)
File "/usr/lib/python3/dist-packages/borg/archiver.py", line 81, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 247, in do_create
    create_inner(archive, cache)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 219, in create_inner
    read_special=args.read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 301, in _process     read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 301, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 275, in _process
     status = archive.process_file(path, st, cache, self.ignore_inode)
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 683, in process_file
    item.update(self.stat_attrs(st, path))
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 573, in stat_attrs
    xattrs = xattr.get_all(path, follow_symlinks=False)
  File "/usr/lib/python3/dist-packages/borg/xattr.py", line 31, in get_all
    for name in listxattr(path, follow_symlinks=follow_symlinks))
  File "/usr/lib/python3/dist-packages/borg/xattr.py", line 115, in listxattr
    raise Exception('listxattr failed')
Exception: listxattr failed

Platform: Linux brain2 3.13.0-92-generic #139-Ubuntu SMP Tue Jun 28 20:42:26 UTC 2016 x86_64 x86_64
Linux: Ubuntu 14.04 trusty
Borg: 1.0.6  Python: CPython 3.4.3
PID: 21726  CWD: /home/administrator
sys.argv: ['/usr/bin/borg', 'create', '-v', '--show-rc', '--stats', '-C', 'lz4', '/data/store/borg::Public-20160810', '/data/Public']
SSH_ORIGINAL_COMMAND: None

terminating with error status, rc 2
```

**Comment by ThomasWaldmann** [comment]
@pepa65 can you file this at https://github.com/borgbackup/borg/issues and delete your post above?

The code at that place may or may not be still the same, so better use the correct issue tracker to not cause confusion.

**Comment by pepa65** [comment]
OK. I thought it might be helpful to know that this issue can still be found in more current code.
Posted on #1462

**Comment by ThomasWaldmann** [comment]
OK, let's delete the borg specific stuff now here.

**Comment by khouli** [comment]
I believe I've run into the same issue as the OP from 2 years ago and I'm using a recent version of attic. I run attic through a systemd task and lately it has been failing. Here's the error output from systemd:

```
$USER@$HOST:~$ systemctl status attic
● attic.service - Backup via attic
   Loaded: loaded (/etc/systemd/system/attic.service; static; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sat 2016-09-10 23:33:35 EDT; 12min ago
  Process: 5437 ExecStart=/root/attic.sh (code=exited, status=1/FAILURE)
 Main PID: 5437 (code=exited, status=1/FAILURE)

$DATE_AND_TIME $HOST attic.sh[5437]:   File "/usr/lib/python3.5/site-packages/attic/archive.py", line 365, in stat_attrs
$DATE_AND_TIME $HOST attic.sh[5437]:     xattrs = xattr.get_all(path, follow_symlinks=False)
$DATE_AND_TIME $HOST attic.sh[5437]:   File "/usr/lib/python3.5/site-packages/attic/xattr.py", line 25, in get_all
$DATE_AND_TIME $HOST attic.sh[5437]:     for name in listxattr(path, follow_symlinks=follow_symlinks))
$DATE_AND_TIME $HOST attic.sh[5437]:   File "/usr/lib/python3.5/site-packages/attic/xattr.py", line 68, in listxattr
$DATE_AND_TIME $HOST attic.sh[5437]:     raise Exception('listxattr failed')
$DATE_AND_TIME $HOST attic.sh[5437]: Exception: listxattr failed
$DATE_AND_TIME $HOST systemd[1]: attic.service: Main process exited, code=exited, status=1/FAILURE
$DATE_AND_TIME $HOST systemd[1]: attic.service: Unit entered failed state.
$DATE_AND_TIME $HOST systemd[1]: attic.service: Failed with result 'exit-code'.
```

My OS is Arch Linux. Attic reports itself in the help as version 0.16. Does this look like a match for this issue and if so, what other info should I provide to help?
