### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by atanasterziyski** [jborg/attic#121]
I am happily using attic 0.13 mostly on FreeBSD systems, however these days I found a weird problem while extracting files (see below). Seems attic cannot extract filenames in Cyrillic, but still no problems with creating or checking the repository with such files. Any clue in which direction I should solve the problem... or at leas temporal workaround?

Traceback (most recent call last):
  File "/usr/local/bin/attic", line 3, in <module>
    main()
  File "/usr/local/lib/python3.3/site-packages/attic/archiver.py", line 715, in main
    exit_code = archiver.run(sys.argv[1:])
  File "/usr/local/lib/python3.3/site-packages/attic/archiver.py", line 705, in run
    return args.func(args)
  File "/usr/local/lib/python3.3/site-packages/attic/archiver.py", line 208, in do_extract
    archive.extract_item(item)
  File "/usr/local/lib/python3.3/site-packages/attic/archive.py", line 237, in extract_item
    st = os.lstat(path)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 21-26: ordinal not in range(128)

**Comment by ThomasWaldmann** [comment]
create FAQ item and close?
