### ISSUE TITLE
Crash when transmitting data to a non-local file system

### ISSUE THREAD

**Issue by SailorOrion** [jborg/attic#122]
When backing up my root file system (initial backup. so empty repo) the process crashes after a random time with the following stacktrace:

Traceback (most recent call last):
  File "/usr/bin/attic", line 3, in <module>
    main()
  File "/usr/lib/python3/dist-packages/attic/archiver.py", line 715, in main
    exit_code = archiver.run(sys.argv[1:])
  File "/usr/lib/python3/dist-packages/attic/archiver.py", line 705, in run
    return args.func(args)
  File "/usr/lib/python3/dist-packages/attic/archiver.py", line 128, in do_create
    self._process(archive, cache, args.excludes, args.exclude_caches, skip_inodes, path, restrict_dev)
  File "/usr/lib/python3/dist-packages/attic/archiver.py", line 177, in _process
    os.path.join(path, filename), restrict_dev)
  File "/usr/lib/python3/dist-packages/attic/archiver.py", line 177, in _process
    os.path.join(path, filename), restrict_dev)
  File "/usr/lib/python3/dist-packages/attic/archiver.py", line 163, in _process
    archive.process_file(path, st, cache)
  File "/usr/lib/python3/dist-packages/attic/archive.py", line 408, in process_file
    self.add_item(item)
  File "/usr/lib/python3/dist-packages/attic/archive.py", line 170, in add_item
    self.write_checkpoint()
  File "/usr/lib/python3/dist-packages/attic/archive.py", line 174, in write_checkpoint
    self.save(self.checkpoint_name)
  File "/usr/lib/python3/dist-packages/attic/archive.py", line 196, in save
    self.manifest.write()
  File "/usr/lib/python3/dist-packages/attic/helpers.py", line 121, in write
    self.repository.put(self.MANIFEST_ID, self.key.encrypt(data))
  File "/usr/lib/python3/dist-packages/attic/remote.py", line 235, in put
    return self.call('put', id_, data, wait=wait)
  File "/usr/lib/python3/dist-packages/attic/remote.py", line 127, in call
    for resp in self.call_many(cmd, [args], **kw):
  File "/usr/lib/python3/dist-packages/attic/remote.py", line 158, in call_many
    raise self.RPCError(error)
attic.remote.RPCError: b'AttributeError'

It happens every time (about 15 attempts now, some with a clean repo, some with as a resume of the previous failed attempt), and every time on another file.

Setup:
Host system with connected CIFS (a synology box), a VM inside that backs up via ssh to the host system. Both systems are running ubuntu server 14.04.1 LTS using python 3.4.0.
It happens both with and without encryption

Any ideas what I'm doing wrong?

**Comment by tgharold** [comment]
I've run into this specific issue when "index.tmp" ends up owned by root:root on the remote system because of doing an "attic check" on the backup repository location while running as root user on the remote system.

(Note to self -- when doing checks of the repository on the remote system, run them with the user account which owns the directory on the remote system.)

**Comment by ThomasWaldmann** [comment]
https://github.com/ThomasWaldmann/attic/commit/954b26f64c903638bd2c195b595ad08a832ef1fa
that would give a bit more info about this. or even write the full traceback to a file...

**Comment by SailorOrion** [comment]
I cannot seem to reproduce the problem using NFS, I will retry with CIFS asap

**Comment by SailorOrion** [comment]
After updating the 'host' (A Synology box), I cannot seem to reproduce any problem with CIFS either. Hence closing

**Comment by parasew** [comment]
just encountered the same problem, as @grugnog mentioned, this is caused by a permission error. reproducible by creating a remote repository with read rights only for the remote user and then starting backup via ssh. the error message could be more explanatory in this case.
