### ISSUE TITLE
TypeError when trying to connect to a remote repository

### ISSUE THREAD

**Issue by lbeltrame** [jborg/attic#127]
This happened out of the blue recently. No updates to attic have been done.

``` python

 attic check sshbackup:mybackup.attic
Traceback (most recent call last):
  File "/usr/bin/attic", line 3, in <module>
    main()
  File "/usr/lib64/python3.4/site-packages/attic/archiver.py", line 715, in main
    exit_code = archiver.run(sys.argv[1:])
  File "/usr/lib64/python3.4/site-packages/attic/archiver.py", line 705, in run
    return args.func(args)
  File "/usr/lib64/python3.4/site-packages/attic/archiver.py", line 69, in do_check
    repository = self.open_repository(args.repository, exclusive=args.repair)
  File "/usr/lib64/python3.4/site-packages/attic/archiver.py", line 32, in open_repository
    repository = RemoteRepository(location, create=create)
  File "/usr/lib64/python3.4/site-packages/attic/remote.py", line 118, in __init__
    version = self.call('negotiate', 1)
  File "/usr/lib64/python3.4/site-packages/attic/remote.py", line 127, in call
    for resp in self.call_many(cmd, [args], **kw):
  File "/usr/lib64/python3.4/site-packages/attic/remote.py", line 173, in call_many
    for type, msgid, error, res in self.unpacker:
TypeError: 'int' object is not iterable
```

In fact the unpacker's **next** method returns ints...

**Comment by ThomasWaldmann** [comment]
see PR #229.
