### ISSUE TITLE
`pip install` on Ubuntu 14.04 fails

### ISSUE THREAD

**Issue by sotte** [jborg/attic#135]
Attic is not as easy to install as the docs imply. Maybe you could mention that `libacl1-dev` must be installed and `pip3` must be used with Ubuntu 14.04.

`pip install --user attic` on a fresh Ubuntu 14.04 fails with

```
Downloading/unpacking attic
  Downloading Attic-0.13.tar.gz (232kB): 232kB downloaded
  Running setup.py (path:/tmp/pip_build_stefan/attic/setup.py) egg_info for package attic
    Attic requires Python 3.2 or later
    Complete output from command python setup.py egg_info:
    Attic requires Python 3.2 or later
```

`pip3 install --user attic` fails with

```
attic/platform_linux.c:344:21: fatal error: sys/acl.h: No such file or directory
 #include "sys/acl.h"
                     ^
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

After installing `libacl1-dev` everything works.

Keep up the great work!

**Comment by alphapapa** [comment]
Had the same problem here.  The final dependency I had to track down was `libssl-dev`, which is the OpenSSL dev files.  The problem is that `openssl` is not in the package name.  And it's not obvious from the error message:
```
Downloading/unpacking Attic from https://pypi.python.org/packages/source/A/Attic/Attic-0.14.tar.gz#md5=34fa12b5acff370b2558f4b0e9490b4c
  Downloading Attic-0.14.tar.gz (233kB): 233kB downloaded
  Running setup.py (path:/tmp/pip_build_me/Attic/setup.py) egg_info for package Attic
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_me/Attic/setup.py", line 76, in <module>
        raise Exception('Unable to find OpenSSL >= 1.0 headers. (Looked here: {})'.format(', '.join(possible_openssl_prefixes)))
    Exception: Unable to find OpenSSL >= 1.0 headers. (Looked here: /usr, /usr/local, /usr/local/opt/openssl, /usr/local/ssl, /usr/local/openssl, /usr/local/attic, /opt/local)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_me/Attic/setup.py", line 76, in <module>

    raise Exception('Unable to find OpenSSL >= 1.0 headers. (Looked here: {})'.format(', '.join(possible_openssl_prefixes)))

Exception: Unable to find OpenSSL >= 1.0 headers. (Looked here: /usr, /usr/local, /usr/local/opt/openssl, /usr/local/ssl, /usr/local/openssl, /usr/local/attic, /opt/local)
```

**Comment by hoxu** [comment]
I created similar issue #360 for Debian Jessie.

**Comment by theilgaard** [comment]
Just had this issue as well.

Fixed by installing `libacl1-dev`

**Comment by Einzelganger** [comment]
I got this working on CentOS 7 by running:
`
yum install gcc openssl openssl-devel python34-pip python34-devel` 
`
pip3 install Attic
`

Considering the lack of updates since 2 years, I think it was best to search for a more active project to use. Perhaps in the future it can be nice to help solve the open issues or create a fork.

**Comment by alphapapa** [comment]
@Einzelganger I've heard the Borg fork is very good.  Planning to give it a try myself.
