### ISSUE TITLE
attic list bombs with "ValueError: year is out of range"

### ISSUE THREAD

**Issue by fukawi2** [jborg/attic#139]
I'm trying to use attic to dump our design department NAS to our backup server. I have mounted the NAS over CIFS with the read-only option, and the dump ran fine (amazing compression/dedupe too; ~800gb resulted in a repo under 160gb!)

When I try to list the archive, I get this:

```
# attic list /bup/cobian/test-nas-dsn.attic::1416970025
drwxrwxrwx 171968813 171966977        0 Nov 25 10:32 mnt/nas-dsn1/WIP
-rw-rw-r-- 171968813 171966977    10244 Nov 14 09:06 mnt/nas-dsn1/WIP/.DS_Store
drwxrwxrwx 171968813 171966977        0 Jun 30 10:05 mnt/nas-dsn1/WIP/.TemporaryItems
<snipped about 30 files from here>
drwxrwxrwx 171968813 171966977        0 Mar 13  2012 mnt/nas-dsn1/WIP/Artwork Master Files/8. Reference
-rwxrwxrwx 171968813 171966977     6148 Mar 13  2012 mnt/nas-dsn1/WIP/Artwork Master Files/8. Reference/.DS_Store
Traceback (most recent call last):
  File "/root/build/prefix/lib/python3.4/site-packages/cx_Freeze/initscripts/Console.py", line 27, in <module>
  File "prefix/bin/attic", line 3, in <module>
  File "/root/build/prefix/lib/python3.4/site-packages/attic/archiver.py", line 715, in main
  File "/root/build/prefix/lib/python3.4/site-packages/attic/archiver.py", line 705, in run
  File "/root/build/prefix/lib/python3.4/site-packages/attic/archiver.py", line 275, in do_list
ValueError: year is out of range
```

It appears to be caused by this directory:

  drwxrwxrwx   2 171968813 171966977    0 May 28  60056 BRIGHTON

I'm not sure exactly how the hell this folder has ended up with the year 60056 (goddam Apple!) and is something else I'll have to investigate, but not sure if there's a more graceful way attic could handle this? As it stands, I don't think I'll be able to restore from this archive.

**Comment by fukawi2** [comment]
Any update on this issue? I can't restore from this repo while attic dies when it comes across this file :(

**Comment by rpodgorny** [comment]
why don't you set the file date to something reasonable (as a workaround)?

**Comment by fukawi2** [comment]
Thanks for the reply. I figured out I can `extract` the files I need, assuming I know the path (which I did in this case). It's only `list` that is affected by this.

I did fix the date (using `touch`) when I originally experienced this, but since then another file came up with this oddity and we didn't know until trying to `list` the repo for a file recovery.

**Comment by ThomasWaldmann** [comment]
Can you please add the attic version to your report above that gave this traceback?

**Comment by ThomasWaldmann** [comment]
I reproduced on current master branch. Working on it.

**Comment by fukawi2** [comment]
Awesome, that looks like it should resolve this issue :)
