### ISSUE TITLE
0.14: out of memory when listing archives

### ISSUE THREAD

**Issue by adept** [jborg/attic#163]
I've been running 0.12 with nommap patch applied up until recently, but seeing how it is included in 0.14, I decided to upgrade. Since the I observe the following regression:

I am not able to "list" two of the three of my repos, attic fails with "Unable to allocate internal buffer"

Details:
I have Backup Box, which has Intel Atom CPU (so, x86_64 arch), 1Gb RAM, 2GB of swap and runs Linux (kernel 3.2.40, distro created by Synology Inc for their NASes). I have Debian chroot on that box, and compiled attic locally (git rev. f342621).

On that box I have three repositories, two backed up locally and one backup up remotely from other host to this box.

Repo | Files | Size(1) | Chunks file size(2) | Can backup | Can list locally(3) | Can list remotely(4)
-------|--------|--------|--------------|---|--------------------|----------------------
A | 79573 | 490 | 705 | Yes | No | No
B | 99968 | 128 | 177 | Yes | No | No
C | 380680 | 62 | 89 | Yes | Yes | No

(1)Size is "Deduplicated size" in Gb
(2)Size of the "cunks" file in the cache for that repo, in Mb
(3)Can list locally while being on Backup Box
(4)From a different Linux box running same attic version, over ssh

Repos "A" and "B" are backed up from local filesystem to local filesystem, repo "C" is backed up from different host (running same attic version) over ssh.

As you can see, I can still succesfully back up to all three repos. I've ran "attic check --repository-only" on them, and it did not find any errors.

Yet when I try "list"ing them (repository, not a specific archive), I get the following exceptions:

Listing repos A, B  locally
```
Traceback (most recent call last):
  File "/usr/local/bin/attic", line 3, in <module>
    main()
  File "/usr/local/lib/python3.3/dist-packages/attic/archiver.py", line 727, in main
    exit_code = archiver.run(sys.argv[1:])
  File "/usr/local/lib/python3.3/dist-packages/attic/archiver.py", line 717, in run
    return args.func(args)
  File "/usr/local/lib/python3.3/dist-packages/attic/archiver.py", line 297, in do_list
    for archive in sorted(Archive.list_archives(repository, key, manifest), key=attrgetter('ts')):
  File "/usr/local/lib/python3.3/dist-packages/attic/archive.py", line 415, in list_archives
    yield Archive(repository, key, manifest, name, cache=cache)
  File "/usr/local/lib/python3.3/dist-packages/attic/archive.py", line 128, in __init__
    self.items_buffer = CacheChunkBuffer(self.cache, self.key, self.stats)
  File "/usr/local/lib/python3.3/dist-packages/attic/archive.py", line 99, in __init__
    super(CacheChunkBuffer, self).__init__(key)
  File "/usr/local/lib/python3.3/dist-packages/attic/archive.py", line 65, in __init__
    self.packer = msgpack.Packer(unicode_errors='surrogateescape')
  File "_packer.pyx", line 73, in msgpack._packer.Packer.__cinit__ (msgpack/_packer.cpp:73)
```

Listing repos A,C remotely:
```
  File "/usr/local/bin/attic", line 3, in <module>
    main()
  File "/usr/local/lib/python3.3/dist-packages/attic/archiver.py", line 727, in main
    exit_code = archiver.run(sys.argv[1:])
  File "/usr/local/lib/python3.3/dist-packages/attic/archiver.py", line 717, in run
    return args.func(args)
  File "/usr/local/lib/python3.3/dist-packages/attic/archiver.py", line 297, in do_list
    for archive in sorted(Archive.list_archives(repository, key, manifest), key=attrgetter('ts')):
  File "/usr/local/lib/python3.3/dist-packages/attic/archive.py", line 415, in list_archives
    yield Archive(repository, key, manifest, name, cache=cache)
  File "/usr/local/lib/python3.3/dist-packages/attic/archive.py", line 145, in __init__
    self.load(info[b'id'])
  File "/usr/local/lib/python3.3/dist-packages/attic/archive.py", line 149, in load
    data = self.key.decrypt(self.id, self.repository.get(self.id))
  File "/usr/local/lib/python3.3/dist-packages/attic/remote.py", line 228, in get
    for resp in self.get_many([id_]):
  File "/usr/local/lib/python3.3/dist-packages/attic/remote.py", line 232, in get_many
    for resp in self.call_many('get', [(id_,) for id_ in ids], is_preloaded=is_preloaded):
  File "/usr/local/lib/python3.3/dist-packages/attic/remote.py", line 193, in call_many
    self.to_send = msgpack.packb((1, self.msgid, cmd, args))
  File "_packer.pyx", line 257, in msgpack._packer.packb (msgpack/_packer.cpp:258)
  File "_packer.pyx", line 73, in msgpack._packer.Packer.__cinit__ (msgpack/_packer.cpp:73)
MemoryError: Unable to allocate internal buffer.
```

Listing repo B remotely:
```
Traceback (most recent call last):
  File "/usr/local/bin/attic", line 3, in <module>
    main()
  File "/usr/local/lib/python3.3/dist-packages/attic/archiver.py", line 727, in main
    exit_code = archiver.run(sys.argv[1:])
  File "/usr/local/lib/python3.3/dist-packages/attic/archiver.py", line 717, in run
    return args.func(args)
  File "/usr/local/lib/python3.3/dist-packages/attic/archiver.py", line 297, in do_list
    for archive in sorted(Archive.list_archives(repository, key, manifest), key=attrgetter('ts')):
  File "/usr/local/lib/python3.3/dist-packages/attic/archive.py", line 415, in list_archives
    yield Archive(repository, key, manifest, name, cache=cache)
  File "/usr/local/lib/python3.3/dist-packages/attic/archive.py", line 145, in __init__
    self.load(info[b'id'])
  File "/usr/local/lib/python3.3/dist-packages/attic/archive.py", line 149, in load
    data = self.key.decrypt(self.id, self.repository.get(self.id))
  File "/usr/local/lib/python3.3/dist-packages/attic/remote.py", line 228, in get
    for resp in self.get_many([id_]):
  File "/usr/local/lib/python3.3/dist-packages/attic/remote.py", line 232, in get_many
    for resp in self.call_many('get', [(id_,) for id_ in ids], is_preloaded=is_preloaded):
  File "/usr/local/lib/python3.3/dist-packages/attic/remote.py", line 171, in call_many
    data = os.read(self.stdout_fd, BUFSIZE)
MemoryError
```

If I happen to know the name of archive within any repo, I could "list" its contents without any issues at all.

PS
Another bit of info that might be a relevant (or might be a red herring) is that I noticed that memory usage for backups to repo A must've increased and tipped over some threshold (not sure because of update 0.12 -> 0.14, or because of the sheer size of all backups or ...), because no-changes-made backup runs that previously took 20-30 minutes took 6-8 hours over the last 5 days, with lots of swapping. I think it might be because attic finally stopped fitting in RAM for that repo - "chunks" file in cache for that repo is 730Mb.

**Comment by jborg** [comment]
How many archives does the repository contain?
As you noticed there's a 10MB buffer allocated for each archive. But I guess you need to have a lot of archives before that starts to hurt.

**Comment by adept** [comment]
Luckily, with my patch I am able to answer that question :)

| Repo | Number of archives|
|---------|----------|
|A|332|
|B|247|
|C|110|

As you can see, 332*10 Mb could easily start to hurt with 1Gb RAM + 2 Gb swap

**Comment by ThomasWaldmann** [comment]
@adept did you meanwhile do more tests for your patch?

**Comment by adept** [comment]
Yes, I am running patched version to create daily backups since since the
day of the original bug report + test restores once a month. No problems
whatsoever.

**Comment by ThomasWaldmann** [comment]
Maybe try the other attic commands also and then do a pull request?
