### ISSUE TITLE
ValueError: too many values to unpack (expected 2) with python-msgpack 0.4.3

### ISSUE THREAD

**Issue by chneukirchen** [jborg/attic#172]
Hi, I updated to python-msgpack 0.4.3 and I'm getting the following error now (on the server, there is python-msgpack 0.4.2.  Both systems run attic 0.14.):

```
Traceback (most recent call last):
  File "/usr/bin/attic", line 3, in <module>
    main()
  File "/usr/lib/python3.4/site-packages/attic/archiver.py", line 727, in main
    exit_code = archiver.run(sys.argv[1:])
  File "/usr/lib/python3.4/site-packages/attic/archiver.py", line 717, in run
    return args.func(args)
  File "/usr/lib/python3.4/site-packages/attic/archiver.py", line 128, in do_create
    self._process(archive, cache, args.excludes, args.exclude_caches, skip_inodes, path, restrict_dev)
  File "/usr/lib/python3.4/site-packages/attic/archiver.py", line 177, in _process
    os.path.join(path, filename), restrict_dev)
  File "/usr/lib/python3.4/site-packages/attic/archiver.py", line 177, in _process
    os.path.join(path, filename), restrict_dev)
  File "/usr/lib/python3.4/site-packages/attic/archiver.py", line 163, in _process
    archive.process_file(path, st, cache)
  File "/usr/lib/python3.4/site-packages/attic/archive.py", line 391, in process_file
    ids = cache.file_known_and_unchanged(path_hash, st)
  File "/usr/lib/python3.4/site-packages/attic/cache.py", line 210, in file_known_and_unchanged
    self._read_files()
  File "/usr/lib/python3.4/site-packages/attic/cache.py", line 84, in _read_files
    for path_hash, item in u:
ValueError: too many values to unpack (expected 2)
```

Listing the contents of prior archives fails too:

```
...
-rw------- root   root    9573731 Jan 02 12:12 boot/initramfs-3.17.1_1.img
-rw------- root   root    9502065 Dec 08 10:09 boot/initramfs-3.17.6_1.img
Traceback (most recent call last):
  File "/usr/bin/attic", line 3, in <module>
    main()
  File "/usr/lib/python3.4/site-packages/attic/archiver.py", line 727, in main
    exit_code = archiver.run(sys.argv[1:])
  File "/usr/lib/python3.4/site-packages/attic/archiver.py", line 717, in run
    return args.func(args)
  File "/usr/lib/python3.4/site-packages/attic/archiver.py", line 275, in do_list
    for item in archive.iter_items():
  File "/usr/lib/python3.4/site-packages/attic/archive.py", line 167, in iter_items
    for item in self.pipeline.unpack_many(self.metadata[b'items'], filter=filter, preload=preload):
  File "/usr/lib/python3.4/site-packages/attic/archive.py", line 45, in unpack_many
    items = [decode_dict(item, (b'path', b'source', b'user', b'group')) for item in unpacker]
  File "/usr/lib/python3.4/site-packages/attic/archive.py", line 45, in <listcomp>
    items = [decode_dict(item, (b'path', b'source', b'user', b'group')) for item in unpacker]
  File "/usr/lib/python3.4/site-packages/msgpack/fallback.py", line 478, in next
    ret = self._fb_unpack(EX_CONSTRUCT, None)
  File "/usr/lib/python3.4/site-packages/msgpack/fallback.py", line 470, in _fb_unpack
    return self._ext_hook(n, obj)
  File "/usr/lib/python3.4/site-packages/msgpack/__init__.py", line 16, in __new__
    raise ValueError("code must be 0~127")
ValueError: code must be 0~127
```

If this is a bug in python-msgpack really, please tell. AFAIU msgpack should be backwards-compatible.

**Comment by chneukirchen** [comment]
nvm, updating to python-msgpack 0.4.4 fixes the issue.
