### ISSUE TITLE
cygwin: "Unable to find OpenSSL>=1.0 Headers"

### ISSUE THREAD

**Issue by jumper444** [jborg/attic#193]
I have cygwin installed which includes (in the 'base' installation):
"libopenssl100: A general purpose cryptography library..."
(v1.0.1k-1)
"openssl: Utilities from the purpose cryptography library..."
(v1.0.1k-1)

As well as me adding:
"python3-openssl: Py3K OpenSSL bindings"
(v0.13.1-1)

Despite this setup attempts to `pip install Attic` results in an error
such that Attic can't find something it needs from OpenSSL. (see below).
Does Attic setup.py need to be adjusted to work with cygwin?
Or does some OTHER setup of OpenSSL need to be installed?
If I install OpenSSL binaries for Windows how would setup.py inside cygwin
access them?  Isn't setup looking for OpenSSL inside the posix env?
And is it looking for header files because something need to be compiled?
Do I need development libraries of OpenSSL (from cygwin) instead?

```
$ pip install Attic
Collecting Attic
  Using cached Attic-0.14.tar.gz
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-r5ywzj/Attic/setup.py", line 76, in <module>
        raise Exception('Unable to find OpenSSL >= 1.0 headers. (Looked here: {})'.format(', '.join(possible_openssl_prefixes)))
    Exception: Unable to find OpenSSL >= 1.0 headers. (Looked here: /usr, /usr/local, /usr/local/opt/openssl, /usr/local/ssl, /usr/local/openssl, /usr/local/attic, /opt/local)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

      File "<string>", line 20, in <module>

      File "/tmp/pip-build-r5ywzj/Attic/setup.py", line 76, in <module>

        raise Exception('Unable to find OpenSSL >= 1.0 headers. (Looked here: {})'.format(', '.join(possible_openssl_prefixes)))

    Exception: Unable to find OpenSSL >= 1.0 headers. (Looked here: /usr, /usr/local, /usr/local/opt/openssl, /usr/local/ssl, /usr/local/openssl, /usr/local/attic, /opt/local)
```

**Comment by jumper444** [comment]
OK...well...installing the OpenSSL development libraries part of cygwin seems to have done the trick.
For the record I added:
"openssl-devel: Files for development of applications which will use OpenSSL"

**Comment by jumper444** [comment]
When I'm finished with all this, assuming I get it working, I can and would like to add information to the project to tell people how to get this working on windows.  Where would I add that and how?
