### ISSUE TITLE
`undefined symbol: EVP_aes_256_ctr` error when running `attic`

### ISSUE THREAD

**Issue by dahjelle** [jborg/attic#197]
Here's the full trace:

```
# attic
Traceback (most recent call last):
  File "/usr/bin/attic", line 2, in <module>
    from attic.archiver import main
  File "/usr/lib64/python3.2/site-packages/attic/archiver.py", line 13, in <module>
    from attic.archive import Archive, ArchiveChecker
  File "/usr/lib64/python3.2/site-packages/attic/archive.py", line 7, in <module>
    from attic.key import key_factory
  File "/usr/lib64/python3.2/site-packages/attic/key.py", line 10, in <module>
    from attic.crypto import pbkdf2_sha256, get_random_bytes, AES, bytes_to_long, long_to_bytes, bytes_to_int, num_aes_blocks
ImportError: /usr/lib64/python3.2/site-packages/attic/crypto.cpython-32mu.so: undefined symbol: EVP_aes_256_ctr
```

Granted, this is on a pretty ancient version of Fedora (16), but in case it is something easy/obvious…it seems to satisfy the listed installation requirements.

**Comment by dahjelle** [comment]
FWIW, I just installed a fresh Python 3.4.2 on that box, and got the same (except for python version numbers) error, so I'm guessing it has something to do with the OpenSSL version?

```
# openssl version
OpenSSL 1.0.0j-fips 10 May 2012
```

**Comment by ThomasWaldmann** [comment]
I researched a bit on the web and found this:
http://ubuntuforums.org/archive/index.php/t-985136.html

In setup.py there is:

    Extension('attic.crypto', [crypto_source], libraries=['crypto'], include_dirs=include_dirs, library_dirs=library_dirs),

Strange, there is no libraries=['ssl', 'crypto'].

I tried that on ubuntu, it works as good as without the 'ssl', so although not needed there, it at least does no harm (AFAICS).

**Comment by dahjelle** [comment]
Thanks for the suggestion & research! I gave it a shot, but still got the same error. Probably should just upgrade that box to CentOS anyway. ;-)

Feel free to close this; just wanted to report it in case it was a more widespread issue. ;-)

**Comment by ThomasWaldmann** [comment]
Did you recompile / reinstall it after changing setup.py?

**Comment by dahjelle** [comment]
Yup—`python3.4 setup.py install`.  The paths changed, but the error message stayed the same.
