### ISSUE TITLE
More user friendly message if repository is on read-only storage

### ISSUE THREAD

**Issue by bjornfor** [jborg/attic#202]
First of all, thanks for this awesome backup software! I am amazed how quick and efficient it is :-)

But it gives rather poor user feedback if the repository is on (remote) read-only storage:

```
$ sudo attic create "bfo@192.168.1.140:/media/3tb/backups/backup.attic::$(hostname)-$(date +%Y%m%dT%H%M%S)" /
Traceback (most recent call last):
  File "/nix/store/b55s23vqkxv3x415999ccnv2w4ri8wqn-attic-0.14/bin/.attic-wrapped", line 4, in <module>
    main()
  File "/nix/store/b55s23vqkxv3x415999ccnv2w4ri8wqn-attic-0.14/lib/python3.4/site-packages/attic/archiver.py", line 727, in main
    exit_code = archiver.run(sys.argv[1:])
  File "/nix/store/b55s23vqkxv3x415999ccnv2w4ri8wqn-attic-0.14/lib/python3.4/site-packages/attic/archiver.py", line 717, in run
    return args.func(args)
  File "/nix/store/b55s23vqkxv3x415999ccnv2w4ri8wqn-attic-0.14/lib/python3.4/site-packages/attic/archiver.py", line 128, in do_create
    self._process(archive, cache, args.excludes, args.exclude_caches, skip_inodes, path, restrict_dev)
  File "/nix/store/b55s23vqkxv3x415999ccnv2w4ri8wqn-attic-0.14/lib/python3.4/site-packages/attic/archiver.py", line 177, in _process
    os.path.join(path, filename), restrict_dev)
  File "/nix/store/b55s23vqkxv3x415999ccnv2w4ri8wqn-attic-0.14/lib/python3.4/site-packages/attic/archiver.py", line 177, in _process
    os.path.join(path, filename), restrict_dev)
  File "/nix/store/b55s23vqkxv3x415999ccnv2w4ri8wqn-attic-0.14/lib/python3.4/site-packages/attic/archiver.py", line 177, in _process
    os.path.join(path, filename), restrict_dev)
  File "/nix/store/b55s23vqkxv3x415999ccnv2w4ri8wqn-attic-0.14/lib/python3.4/site-packages/attic/archiver.py", line 177, in _process
    os.path.join(path, filename), restrict_dev)
  File "/nix/store/b55s23vqkxv3x415999ccnv2w4ri8wqn-attic-0.14/lib/python3.4/site-packages/attic/archiver.py", line 177, in _process
    os.path.join(path, filename), restrict_dev)
  File "/nix/store/b55s23vqkxv3x415999ccnv2w4ri8wqn-attic-0.14/lib/python3.4/site-packages/attic/archiver.py", line 177, in _process
    os.path.join(path, filename), restrict_dev)
  File "/nix/store/b55s23vqkxv3x415999ccnv2w4ri8wqn-attic-0.14/lib/python3.4/site-packages/attic/archiver.py", line 177, in _process
    os.path.join(path, filename), restrict_dev)
  File "/nix/store/b55s23vqkxv3x415999ccnv2w4ri8wqn-attic-0.14/lib/python3.4/site-packages/attic/archiver.py", line 177, in _process
    os.path.join(path, filename), restrict_dev)
  File "/nix/store/b55s23vqkxv3x415999ccnv2w4ri8wqn-attic-0.14/lib/python3.4/site-packages/attic/archiver.py", line 177, in _process
    os.path.join(path, filename), restrict_dev)
  File "/nix/store/b55s23vqkxv3x415999ccnv2w4ri8wqn-attic-0.14/lib/python3.4/site-packages/attic/archiver.py", line 177, in _process
    os.path.join(path, filename), restrict_dev)
  File "/nix/store/b55s23vqkxv3x415999ccnv2w4ri8wqn-attic-0.14/lib/python3.4/site-packages/attic/archiver.py", line 163, in _process
    archive.process_file(path, st, cache)
  File "/nix/store/b55s23vqkxv3x415999ccnv2w4ri8wqn-attic-0.14/lib/python3.4/site-packages/attic/archive.py", line 410, in process_file
    self.add_item(item)
  File "/nix/store/b55s23vqkxv3x415999ccnv2w4ri8wqn-attic-0.14/lib/python3.4/site-packages/attic/archive.py", line 173, in add_item
    self.write_checkpoint()
  File "/nix/store/b55s23vqkxv3x415999ccnv2w4ri8wqn-attic-0.14/lib/python3.4/site-packages/attic/archive.py", line 177, in write_checkpoint
    self.save(self.checkpoint_name)
  File "/nix/store/b55s23vqkxv3x415999ccnv2w4ri8wqn-attic-0.14/lib/python3.4/site-packages/attic/archive.py", line 199, in save
    self.manifest.write()
  File "/nix/store/b55s23vqkxv3x415999ccnv2w4ri8wqn-attic-0.14/lib/python3.4/site-packages/attic/helpers.py", line 121, in write
    self.repository.put(self.MANIFEST_ID, self.key.encrypt(data))
  File "/nix/store/b55s23vqkxv3x415999ccnv2w4ri8wqn-attic-0.14/lib/python3.4/site-packages/attic/remote.py", line 236, in put
    return self.call('put', id_, data, wait=wait)
  File "/nix/store/b55s23vqkxv3x415999ccnv2w4ri8wqn-attic-0.14/lib/python3.4/site-packages/attic/remote.py", line 127, in call
    for resp in self.call_many(cmd, [args], **kw):
  File "/nix/store/b55s23vqkxv3x415999ccnv2w4ri8wqn-attic-0.14/lib/python3.4/site-packages/attic/remote.py", line 160, in call_many
    raise self.RPCError(error)
attic.remote.RPCError: b'AttributeError'
```

**Comment by ThomasWaldmann** [comment]
With a more verbose exception handler, one gets this:
attic.remote.RPCError: AttributeError("'Repository' object has no attribute 'segments'")

**Comment by bjornfor** [comment]
As for the use case: I like to have my backup disk mounted read-only most of the time. I mount it read-write only when running the backup job.

**Comment by ThomasWaldmann** [comment]
A little less confusing with PR #228.

Maybe not the final solution though, which could be a pretty and clear error msg.
