### ISSUE TITLE
Fails on ARM32, including testsuite fails

### ISSUE THREAD

**Issue by sourcejedi** [jborg/attic#203]
`attic create` fails on my ARM32, with "assert segments[segment] == 0" as per #196.

 The testsuite also fails.  Some of the errors look like the same assert.  (To get the unittest.mock on Debian 7, I had to create a python-3.4 virtualenv)

Transcript here: https://gist.github.com/sourcejedi/adbe245af22694f69189

Selected testsuite errors from full transcript:

    ======================================================================
    ERROR: test_aes_counter_uniqueness_keyfile (attic.testsuite.archiver.ArchiverTestCase)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
    File "/home/alan/src/Attic-0.14/virtualenv-3.4.2/lib/python3.4/site-packages/Attic-0.14-py3.4-linux-armv5tel.egg/attic/testsuite/archiver.py", line 381, in test_aes_counter_uniqueness_keyfile
    self.verify_aes_counter_uniqueness('keyfile')
    File "/home/alan/src/Attic-0.14/virtualenv-3.4.2/lib/python3.4/site-packages/Attic-0.14-py3.4-linux-armv5tel.egg/attic/testsuite/archiver.py", line 368, in verify_aes_counter_uniqueness
    self.create_test_files()
    File "/home/alan/src/Attic-0.14/virtualenv-3.4.2/lib/python3.4/site-packages/Attic-0.14-py3.4-linux-armv5tel.egg/attic/testsuite/archiver.py", line 124, in create_test_files
    os.utime('input/empty', (19880895600, 19880895600))
    OverflowError: timestamp out of range for platform time_t 

    ======================================================================
    ERROR: test_cmdline_compatibility (attic.testsuite.archiver.RemoteArchiverTestCase)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
    File "/home/alan/src/Attic-0.14/virtualenv-3.4.2/lib/python3.4/site-packages/Attic-0.14-py3.4-linux-armv5tel.egg/attic/testsuite/archiver.py", line 284, in test_cmdline_compatibility
    self.attic('create', self.repository_location + '::test', 'input')
    File "/home/alan/src/Attic-0.14/virtualenv-3.4.2/lib/python3.4/site-packages/Attic-0.14-py3.4-linux-armv5tel.egg/attic/testsuite/archiver.py", line 94, in attic
    ret = self.archiver.run(args)
    File "/home/alan/src/Attic-0.14/virtualenv-3.4.2/lib/python3.4/site-packages/Attic-0.14-py3.4-linux-armv5tel.egg/attic/archiver.py", line 717, in run
    return args.func(args)
    File "/home/alan/src/Attic-0.14/virtualenv-3.4.2/lib/python3.4/site-packages/Attic-0.14-py3.4-linux-armv5tel.egg/attic/archiver.py", line 129, in do_create
    archive.save()
    File "/home/alan/src/Attic-0.14/virtualenv-3.4.2/lib/python3.4/site-packages/Attic-0.14-py3.4-linux-armv5tel.egg/attic/archive.py", line 200, in save
    self.repository.commit()
    File "/home/alan/src/Attic-0.14/virtualenv-3.4.2/lib/python3.4/site-packages/Attic-0.14-py3.4-linux-armv5tel.egg/attic/remote.py", line 216, in commit
    return self.call('commit')
    File "/home/alan/src/Attic-0.14/virtualenv-3.4.2/lib/python3.4/site-packages/Attic-0.14-py3.4-linux-armv5tel.egg/attic/remote.py", line 127, in call
    for resp in self.call_many(cmd, [args], **kw):
    File "/home/alan/src/Attic-0.14/virtualenv-3.4.2/lib/python3.4/site-packages/Attic-0.14-py3.4-linux-armv5tel.egg/attic/remote.py", line 160, in call_many
    raise self.RPCError(error)
    attic.remote.RPCError: b'AssertionError' 

    ======================================================================
    ERROR: test_repair_corrupted_commit_segment (attic.testsuite.repository.RemoteRepositoryCheckTestCase)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
    File "/home/alan/src/Attic-0.14/virtualenv-3.4.2/lib/python3.4/site-packages/Attic-0.14-py3.4-linux-armv5tel.egg/attic/testsuite/repository.py", line 271, in test_repair_corrupted_commit_segment
    self.get_objects(3)
    File "/home/alan/src/Attic-0.14/virtualenv-3.4.2/lib/python3.4/site-packages/Attic-0.14-py3.4-linux-armv5tel.egg/attic/testsuite/repository.py", line 199, in get_objects
    self.repository.get(('%032d' % id_).encode('ascii'))
    File "/home/alan/src/Attic-0.14/virtualenv-3.4.2/lib/python3.4/site-packages/Attic-0.14-py3.4-linux-armv5tel.egg/attic/remote.py", line 228, in get
    for resp in self.get_many([id_]):
    File "/home/alan/src/Attic-0.14/virtualenv-3.4.2/lib/python3.4/site-packages/Attic-0.14-py3.4-linux-armv5tel.egg/attic/remote.py", line 232, in get_many
    for resp in self.call_many('get', [(id_,) for id_ in ids], is_preloaded=is_preloaded):
    File "/home/alan/src/Attic-0.14/virtualenv-3.4.2/lib/python3.4/site-packages/Attic-0.14-py3.4-linux-armv5tel.egg/attic/remote.py", line 160, in call_many
    raise self.RPCError(error)
    attic.remote.RPCError: b'FileNotFoundError' 

    ======================================================================
    ERROR: test_repair_missing_index (attic.testsuite.repository.RepositoryCheckTestCase)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
    File "/home/alan/src/Attic-0.14/virtualenv-3.4.2/lib/python3.4/site-packages/Attic-0.14-py3.4-linux-armv5tel.egg/attic/repository.py", line 474, in get_fd
    return self.fds[segment]
    File "/home/alan/src/Attic-0.14/virtualenv-3.4.2/lib/python3.4/site-packages/Attic-0.14-py3.4-linux-armv5tel.egg/attic/lrucache.py", line 24, in __getitem__
    return super(LRUCache, self).__getitem__(key)
    KeyError: 875560961
 
    During handling of the above exception, another exception occurred:
 
    Traceback (most recent call last):
    File "/home/alan/src/Attic-0.14/virtualenv-3.4.2/lib/python3.4/site-packages/Attic-0.14-py3.4-linux-armv5tel.egg/attic/testsuite/repository.py", line 293, in test_repair_missing_index
    self.get_objects(4)
    File "/home/alan/src/Attic-0.14/virtualenv-3.4.2/lib/python3.4/site-packages/Attic-0.14-py3.4-linux-armv5tel.egg/attic/testsuite/repository.py", line 199, in get_objects
    self.repository.get(('%032d' % id_).encode('ascii'))
    File "/home/alan/src/Attic-0.14/virtualenv-3.4.2/lib/python3.4/site-packages/Attic-0.14-py3.4-linux-armv5tel.egg/attic/repository.py", line 338, in get
    return self.io.read(segment, offset, id_)
    File "/home/alan/src/Attic-0.14/virtualenv-3.4.2/lib/python3.4/site-packages/Attic-0.14-py3.4-linux-armv5tel.egg/attic/repository.py", line 538, in read
    fd = self.get_fd(segment)
    File "/home/alan/src/Attic-0.14/virtualenv-3.4.2/lib/python3.4/site-packages/Attic-0.14-py3.4-linux-armv5tel.egg/attic/repository.py", line 476, in get_fd
    fd = open(self.segment_filename(segment), 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpwtrgnnqe/repository/data/87556/875560961

    ======================================================================
    FAIL: test_check_usage (attic.testsuite.archiver.ArchiverCheckTestCase)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
    File "/home/alan/src/Attic-0.14/virtualenv-3.4.2/lib/python3.4/site-packages/Attic-0.14-py3.4-linux-armv5tel.egg/attic/testsuite/archiver.py", line 393, in setUp
    self.create_src_archive('archive1')
    File "/home/alan/src/Attic-0.14/virtualenv-3.4.2/lib/python3.4/site-packages/Attic-0.14-py3.4-linux-armv5tel.egg/attic/testsuite/archiver.py", line 104, in create_src_archive
    self.attic('create', self.repository_location + '::' + name, src_dir)
    File "/home/alan/src/Attic-0.14/virtualenv-3.4.2/lib/python3.4/site-packages/Attic-0.14-py3.4-linux-armv5tel.egg/attic/testsuite/archiver.py", line 94, in attic
    ret = self.archiver.run(args)
    File "/home/alan/src/Attic-0.14/virtualenv-3.4.2/lib/python3.4/site-packages/Attic-0.14-py3.4-linux-armv5tel.egg/attic/archiver.py", line 717, in run
    return args.func(args)
    File "/home/alan/src/Attic-0.14/virtualenv-3.4.2/lib/python3.4/site-packages/Attic-0.14-py3.4-linux-armv5tel.egg/attic/archiver.py", line 129, in do_create
    archive.save()
    File "/home/alan/src/Attic-0.14/virtualenv-3.4.2/lib/python3.4/site-packages/Attic-0.14-py3.4-linux-armv5tel.egg/attic/archive.py", line 200, in save
    self.repository.commit()
    File "/home/alan/src/Attic-0.14/virtualenv-3.4.2/lib/python3.4/site-packages/Attic-0.14-py3.4-linux-armv5tel.egg/attic/repository.py", line 130, in commit
    self.compact_segments()
    File "/home/alan/src/Attic-0.14/virtualenv-3.4.2/lib/python3.4/site-packages/Attic-0.14-py3.4-linux-armv5tel.egg/attic/repository.py", line 194, in compact_segments
    assert segments[segment] == 0
    AssertionError 

    ======================================================================
    FAIL: test_chunkindex (attic.testsuite.hashindex.HashIndexTestCase)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
    File "/home/alan/src/Attic-0.14/virtualenv-3.4.2/lib/python3.4/site-packages/Attic-0.14-py3.4-linux-armv5tel.egg/attic/testsuite/hashindex.py", line 50, in test_chunkindex
    self._generic_test(ChunkIndex, lambda x: (x, x, x), 'ed22e8a883400453c0ee79a06c54df72c994a54eeefdc6c0989efdc5ee6d07b7')
    File "/home/alan/src/Attic-0.14/virtualenv-3.4.2/lib/python3.4/site-packages/Attic-0.14-py3.4-linux-armv5tel.egg/attic/testsuite/hashindex.py", line 18, in _generic_test
    self.assert_equal(idx[bytes('%-32d' % x, 'ascii')], make_value(x))
    AssertionError: Tuples differ: (538968064, 0, 0) != (0, 0, 0)
 
    First differing element 0:
    538968064
 
    ======================================================================
    FAIL: test_nsindex (attic.testsuite.hashindex.HashIndexTestCase)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
    File "/home/alan/src/Attic-0.14/virtualenv-3.4.2/lib/python3.4/site-packages/Attic-0.14-py3.4-linux-armv5tel.egg/attic/testsuite/hashindex.py", line 47, in test_nsindex
    self._generic_test(NSIndex, lambda x: (x, x), '369a18ae6a52524eb2884a3c0fdc2824947edd017a2688c5d4d7b3510c245ab9')
    File "/home/alan/src/Attic-0.14/virtualenv-3.4.2/lib/python3.4/site-packages/Attic-0.14-py3.4-linux-armv5tel.egg/attic/testsuite/hashindex.py", line 18, in _generic_test
    self.assert_equal(idx[bytes('%-32d' % x, 'ascii')], make_value(x))
    AssertionError: Tuples differ: (538968064, 0) != (0, 0)
 
    First differing element 0:
    538968064
    0
 
    - (538968064, 0)
    + (0, 0)
 
    ======================================================================
    FAIL: test_resize (attic.testsuite.hashindex.HashIndexTestCase)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
    File "/home/alan/src/Attic-0.14/virtualenv-3.4.2/lib/python3.4/site-packages/Attic-0.14-py3.4-linux-armv5tel.egg/attic/testsuite/hashindex.py", line 67, in test_resize
    self.assert_equal(initial_size, os.path.getsize(idx_name.name))
    AssertionError: 40978 != 163858
 
    ----------------------------------------------------------------------
    Ran 112 tests in 371.961s
 
    FAILED (failures=20, errors=44, skipped=8)

**Comment by sourcejedi** [comment]
Sorry, I didn't notice #196 showed the testsuite failures as well.  Closed as duplicate.
