### ISSUE TITLE
Unable to resume backups

### ISSUE THREAD

**Issue by Sedins** [jborg/attic#220]
Unable to resume backup which is mentioned in the faq https://attic-backup.org/faq.html

Running Attic 0.14 installed with pip3 on Ubuntu 14.04 LTS 64bit

1. Open connection to SSH (in my case a Synology DS411j NAS):
    sshfs admin@192.168.1.20:/homes/admin/backup /mnt/backup
2. Start a long-running backup job on Ubuntu to an initialized remote repository over SSHFS:
    attic create -v -s -c 30 /mnt/backup/test3.attic::test-6 /mnt/public/testar
3. Wait for a minimum of 5 minutes (or specify a shorter period of time with -c parameter above)
3. Reboot NAS
4. Attic crashes with the error message below
5. Check backup size on NAS which has increased: du -d 1 -h .
6. Searching for <archive-name>.snapshot doesn't result in any hits, neither at source or destination
7. Re-opening connection and starting the backup again results in uploading all data again

Thankful for swift response as this functionality really is important to me when doing long backup sessions. If more information is needed I'll be glad to recreate and send it over. Thanks in advance.

Regards,
Stefan

Enter passphrase for /mnt/backup/test3.attic::test-6:
/mnt/public/testar
/mnt/public/testar/0.txt
/mnt/public/testar/Try 1
/mnt/public/testar/Try 1/Try.iso
attic: /mnt/public/testar/Try 1/Try.iso: [Errno 107] Transport endpoint is not connected
/mnt/public/testar/Try 1/Try.txt
attic: /mnt/public/testar/Try 1/Try.txt: [Errno 107] Transport endpoint is not connected
/mnt/public/testar/Try 2 - Trys
Traceback (most recent call last):
  File "/usr/local/bin/attic", line 3, in <module>
    main()
  File "/usr/local/lib/python3.4/dist-packages/attic/archiver.py", line 727, in main
    exit_code = archiver.run(sys.argv[1:])
  File "/usr/local/lib/python3.4/dist-packages/attic/archiver.py", line 717, in run
    return args.func(args)
  File "/usr/local/lib/python3.4/dist-packages/attic/archiver.py", line 128, in do_create
    self._process(archive, cache, args.excludes, args.exclude_caches, skip_inodes, path, restrict_dev)
  File "/usr/local/lib/python3.4/dist-packages/attic/archiver.py", line 177, in _process
    os.path.join(path, filename), restrict_dev)
  File "/usr/local/lib/python3.4/dist-packages/attic/archiver.py", line 169, in _process
    archive.process_item(path, st)
  File "/usr/local/lib/python3.4/dist-packages/attic/archive.py", line 365, in process_item
    self.add_item(item)
  File "/usr/local/lib/python3.4/dist-packages/attic/archive.py", line 173, in add_item
    self.write_checkpoint()
  File "/usr/local/lib/python3.4/dist-packages/attic/archive.py", line 177, in write_checkpoint
    self.save(self.checkpoint_name)
  File "/usr/local/lib/python3.4/dist-packages/attic/archive.py", line 200, in save
    self.repository.commit()
  File "/usr/local/lib/python3.4/dist-packages/attic/repository.py", line 129, in commit
    self.io.write_commit()
  File "/usr/local/lib/python3.4/dist-packages/attic/repository.py", line 574, in write_commit
    self.close_segment()
  File "/usr/local/lib/python3.4/dist-packages/attic/repository.py", line 580, in close_segment
    os.fsync(self._write_fd)
OSError: [Errno 107] Transport endpoint is not connected
Exception ignored in: <bound method Repository.__del__ of <attic.repository.Repository object at 0x7f1e00a24ef0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/attic/repository.py", line 61, in __del__
    self.close()
  File "/usr/local/lib/python3.4/dist-packages/attic/repository.py", line 121, in close
    self.io.close()
  File "/usr/local/lib/python3.4/dist-packages/attic/repository.py", line 406, in close
    self.fds.pop(segment).close()
OSError: [Errno 107] Transport endpoint is not connected

**Comment by adept** [comment]
".snapshot" would be appended to the name of the archive, as seen in the
output of "attic list" command.

Try listing your repository and check if you have snapshort archives there.
Provided that you rebooted your NAS after snapshot creation period, you
should see some.

On Fri, Mar 6, 2015 at 2:27 PM, Sedins <notifications@github.com> wrote:

> Unable to resume backup which is mentioned in the faq
> https://attic-backup.org/faq.html
>
> Running Attic 0.14 installed with pip3 on Ubuntu 14.04 LTS 64bit
>
>    1. Open connection to SSH (in my case a Synology DS411j NAS): sshfs
>    admin@192.168.1.20:/homes/admin/backup /mnt/backup
>    2. Start a long-running backup job on Ubuntu to an initialized remote
>    repository over SSHFS: attic create -v -s -c 30
>    /mnt/backup/test3.attic::test-6 /mnt/public/testar
>    3. Wait for a minimum of 5 minutes (or specify a shorter period of
>    time with -c parameter above)
>    4. Reboot NAS
>    5. Attic crashes with the error message below
>    6. Check backup size on NAS which has increased: du -d 1 -h .
>    7. Searching for .snapshot doesn't result in any hits, neither at
>    source or destination
>    8. Re-opening connection and starting the backup again results in
>    uploading all data again
>
> Thankful for swift response as this functionality really is important to
> me when doing long backup sessions. If more information is needed I'll be
> glad to recreate and send it over. Thanks in advance.
>
> Regards,
> Stefan
>
> Enter passphrase for /mnt/backup/test3.attic::test-6:
> /mnt/public/testar
> /mnt/public/testar/0.txt
> /mnt/public/testar/Try 1
> /mnt/public/testar/Try 1/Try.iso
> attic: /mnt/public/testar/Try 1/Try.iso: [Errno 107] Transport endpoint is
> not connected
> /mnt/public/testar/Try 1/Try.txt
> attic: /mnt/public/testar/Try 1/Try.txt: [Errno 107] Transport endpoint is
> not connected
> /mnt/public/testar/Try 2 - Trys
> Traceback (most recent call last):
> File "/usr/local/bin/attic", line 3, in
> main()
> File "/usr/local/lib/python3.4/dist-packages/attic/archiver.py", line 727,
> in main
> exit_code = archiver.run(sys.argv[1:])
> File "/usr/local/lib/python3.4/dist-packages/attic/archiver.py", line 717,
> in run
> return args.func(args)
> File "/usr/local/lib/python3.4/dist-packages/attic/archiver.py", line 128,
> in do_create
> self.
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
> *process(archive, cache, args.excludes, args.exclude_caches, skip_inodes,
> path, restrict_dev) File
> "/usr/local/lib/python3.4/dist-packages/attic/archiver.py", line 177, in
> process os.path.join(path, filename), restrict_dev) File
> "/usr/local/lib/python3.4/dist-packages/attic/archiver.py", line 169, in
> _process archive.process_item(path, st) File
> "/usr/local/lib/python3.4/dist-packages/attic/archive.py", line 365, in
> process_item self.add_item(item) File
> "/usr/local/lib/python3.4/dist-packages/attic/archive.py", line 173, in
> add_item self.write_checkpoint() File
> "/usr/local/lib/python3.4/dist-packages/attic/archive.py", line 177, in
> write_checkpoint self.save(self.checkpoint_name) File
> "/usr/local/lib/python3.4/dist-packages/attic/archive.py", line 200, in
> save self.repository.commit() File
> "/usr/local/lib/python3.4/dist-packages/attic/repository.py", line 129, in
> commit self.io.write_commit() File
> "/usr/local/lib/python3.4/dist-packages/attic/repository.py", line 574, in
> write_commit self.close_segment() File
> "/usr/local/lib/python3.4/dist-packages/attic/repository.py", line 580, in
> close_segment os.fsync(self._write_fd) OSError: [Errno 107] Transport
> endpoint is not connected Exception ignored in: <bound method
> Repository.__del* of >
> Traceback (most recent call last):
> File "/usr/local/lib/python3.4/dist-packages/attic/repository.py", line
> 61, in *del*
> self.close()
> File "/usr/local/lib/python3.4/dist-packages/attic/repository.py", line
> 121, in close
> self.io.close()
> File "/usr/local/lib/python3.4/dist-packages/attic/repository.py", line
> 406, in close
> self.fds.pop(segment).close()
> OSError: [Errno 107] Transport endpoint is not connected
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jborg/attic/issues/220>.
>



-- 
Dmitry Astapov

**Comment by Sedins** [comment]
Have tried this before, but doing it again to show output with backup to test-7:

# attic create -v --stats -c 20 /mnt/backup/test3.attic::test-7 /mnt/public/Upload/testar
< rebooted NAS after the snapshot should have been written and waited for it to come up again >
# sshfs...
# attic list /mnt/backup/test3.attic
Enter passphrase for /mnt/backup/test3.attic:
<--- removed rows with test1 to 4 --->
test-5                               Thu Mar  5 21:21:58 2015
test-6                               Fri Mar  6 00:45:05 2015

Test-7 is not displayed at all in the list. Weird as it should have been written already?

**Comment by adept** [comment]
I guess in this particular case attic could only bes good as the underlying
file system. My guess would be that sshfs does something weird with
flushing writes to "disk".

Would you get a ".snapshot" if you just kill the attic process?

PS
I have 412+, and I just installed debian chroot there, installed attic in
chroot and do my backups over ssh - I found this to be faster and less
brittle than backups to mounted file system

On Fri, Mar 6, 2015 at 2:54 PM, Sedins <notifications@github.com> wrote:

> Have tried this before, but doing it again to show output with backup to
> test-7:
> attic create -v --stats -c 20 /mnt/backup/test3.attic::test-7
> /mnt/public/Upload/testar
>
> < rebooted NAS after the snapshot should have been written and waited for
> it to come up again >
> sshfs... attic list /mnt/backup/test3.attic
>
> Enter passphrase for /mnt/backup/test3.attic:
> <--- removed rows with test1 to 4 --->
> test-5 Thu Mar 5 21:21:58 2015
> test-6 Fri Mar 6 00:45:05 2015
>
> Test-7 is not displayed at all in the list. Weird as it should have been
> written already?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jborg/attic/issues/220#issuecomment-77570930>.
>



-- 
Dmitry Astapov

**Comment by Sedins** [comment]
No snapshot even if I just killed the attic process :/

Installing attic directly on the NAS was also my first choice. But I could not find pip3 after installing python3 through the package manager and do not have that much knowledge about python in general so resorted to sshfs.

Do you know if there are any information somewhere on how to install debian chroot and then attic inside of the jail?

**Comment by adept** [comment]
Well, then it could be that you are pulling the plug too early: snapshot is
created after 5 minutes, but it still takes some time to write it down. Try
waiting a bit more. Or try on the local fs first to check that
snapshotting happens when you think it happens.

As for setting up attic under chroot, I dont remember anything special
about it. Debian Chroot is available as Synology package (via SynoCommunity
repo), and after you set it up, you can just follow
whatever process you used for Ubuntu to install it in chroot.

On Fri, Mar 6, 2015 at 3:06 PM, Sedins <notifications@github.com> wrote:

> No snapshot even if I just killed the attic process :/
>
> Installing attic directly on the NAS was also my first choice. But I could
> not find pip3 after installing python3 through the package manager and do
> not have that much knowledge about python in general so resorted to sshfs.
>
> Do you know if there are any information somewhere on how to install
> debian chroot and then attic inside of the jail?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jborg/attic/issues/220#issuecomment-77573014>.
>



-- 
Dmitry Astapov

**Comment by Sedins** [comment]
Tested more now.

Local source and destination ext3 filesystem always creates a checkpoint.
Local ext3 source to sshfs destination always creates a checkpoint.

CIFS source to local ext3 or sshfs seems flaky. I was able to get some checkpoints and also resume them to create full snapshots. Suddenly (the 4th or 5th) checkpoints were not being created any longer on that particular archive from CIFS.

This is what my fstab looks like:
//192.168.1.11/public  /mnt/public  cifs  username=<user>,iocharset=utf8,sec=ntlm  0  0

**Comment by ThomasWaldmann** [comment]
That the source influences behaviour at the target sounds strange. Could it be just coincidence?

**Comment by Sedins** [comment]
I don't think so. Tested it a lot and every time I get the source from ext3 it's able to create a checkpoint, but as soon as the source is the CIFS share Attic is unable to create it. Reproduces every time with the same outcome.

I'm killing the attic process to reproduce this, but I think it's the same if I reboot the destination or use some other method of interrupting the transfer.

**Comment by Sedins** [comment]
Attic not creating checkpoints: Steps to reproduce

1. Create backup on Linux-volume (ext3 in my case): attic init -e passphrase test.attic
2. Mount CIFS share (Win2008R2 in my case): mount -t cifs -o username=<user> //192.168.1.x/share /mnt/share
3. Create archive from CIFS share: attic create -v -s -c 20 test.attic::test-1 /mnt/share/folder
4. Kill attic process from another terminal after checkpoint should have been created: killall attic
5. Check if checkpoint exists (in my case never if source is CIFS): attic list test.attic

**Comment by Sedins** [comment]
After reading up on the source code I figured it out.

Checkpoints are written 5 minutes apart (or some other time specified with the -c parameter) BUT the check for when to write it is just being done when beginning to process a new file.

The files being backed up from the CIFS share were very large and each took way longer than 5 minutes to complete. This made me kill the attic process before the next file was being processed and thus no checkpoint was created neither.

This results in big files (f.ex. virtual machine images) always has to be resumed from scratch if transfer is broken. Presumably it has to be this way for the file backup to work.

Learned something in the process as it involved some digging around in the code and maybe this information could be useful to someone else someday as well. Resume functionality (checkpoint creation) could be explained further in the documentation, but no big problem I guess. This issue can be closed.

**Comment by ThomasWaldmann** [comment]
The remaining question might be whether checkpoints could be made not just in-between files.

Could be useful for your case (just some big files in between other files) as well as other usecases like full-disk image backups (like reading all from /dev/sda or /dev/vg/foo-snapshot in one piece).
So, re-open?

**Comment by Sedins** [comment]
Yes, would be great if resuming in the midst of files is possible to do and to update the checkpoint accordingly. Re-opening and hope it'll be possible to add this change.

**Comment by tscheggsches** [comment]
I can verify this. I just tried to upload a big 20GB VDI-File over shaky sshfs and no checkpoint was created while transfering this file. It would definitely be great to have mid-file checkpoints!

**Comment by ThomasWaldmann** [comment]
@Sedins could you change issue title to "implement mid-file checkpoints?"?

**Comment by Sedins** [comment]
Good point. Changed the title so it matches the issue better.
