### ISSUE TITLE
Traceback when running 'check --repair' on a repository

### ISSUE THREAD

**Issue by Ernest0x** [jborg/attic#232]
I got the following when running 'check --repair' on a repository. It seems that the code found some damage that could not handle.

    ...
    Archive metadata damage detected
    Traceback (most recent call last):
      File "/usr/local/bin/attic", line 5, in <module>
        pkg_resources.run_script('Attic==0.13', 'attic')
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 499, in run_script
        self.require(requires)[0].run_script(script_name, ns)
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 1236, in run_script
        exec(compile(open(script_filename).read(), script_filename, 'exec'), namespace, namespace)
      File "/usr/local/lib/python3.2/dist-packages/Attic-0.13-py3.2-linux-x86_64.egg/EGG-INFO/scripts/attic", line 3, in <module>
        main()
      File "/usr/local/lib/python3.2/dist-packages/Attic-0.13-py3.2-linux-x86_64.egg/attic/archiver.py", line 715, in main
        exit_code = archiver.run(sys.argv[1:])
      File "/usr/local/lib/python3.2/dist-packages/Attic-0.13-py3.2-linux-x86_64.egg/attic/archiver.py", line 705, in run
        return args.func(args)
      File "/usr/local/lib/python3.2/dist-packages/Attic-0.13-py3.2-linux-x86_64.egg/attic/archiver.py", line 84, in do_check
        if not args.repo_only and not ArchiveChecker().check(repository, repair=args.repair):
      File "/usr/local/lib/python3.2/dist-packages/Attic-0.13-py3.2-linux-x86_64.egg/attic/archive.py", line 494, in check
        self.rebuild_refcounts()
      File "/usr/local/lib/python3.2/dist-packages/Attic-0.13-py3.2-linux-x86_64.egg/attic/archive.py", line 646, in rebuild_refcounts
        items_buffer.add(item)
      File "/usr/local/lib/python3.2/dist-packages/Attic-0.13-py3.2-linux-x86_64.egg/attic/archive.py", line 69, in add
        self.buffer.write(self.packer.pack(StableDict(item)))
    TypeError: cannot convert dictionary update sequence element #0 to a sequence

**Comment by ThomasWaldmann** [comment]
Could you use attic 0.14 and try again? Just to make sure we do not look at already fixed bugs.

**Comment by Ernest0x** [comment]
> Could you use attic 0.14 and try again? Just to make sure we do not look at already fixed bugs.

The same error occurs with attic 0.14 too.

**Comment by ThomasWaldmann** [comment]
If you could add a little code and look for the output, it would help analysing the problem:

In file /usr/local/lib/python3.2/dist-packages/Attic-0.13-py3.2-linux-x86_64.egg/attic/archive.py", before line 69 (self.buffer.write(self.packer.pack(StableDict(item)))), add:

print(repr(item))
print(repr(StableDict(item)))

Indent these lines same as the following line. Post the output here (should show up at top of the traceback)).

**Comment by Ernest0x** [comment]
The traceback occurs when trying to analyze a specific archive. Here is the output just before the traceback, after adding the print() calls above:

    Analyzing archive binlogs_2015-03-09-02:25 (364/2074)
    {b'path': b'var/lib/mysql/binlog.020441', b'gid': 108, b'group': b'mysql', b'mode': 33200, b'mtime': 1425027901071324160}
    {b'path': b'var/lib/mysql/binlog.020441', b'gid': 108, b'group': b'mysql', b'mode': 33200, b'mtime': 1425027901071324160}
    b'uid'

**Comment by Ernest0x** [comment]
Also, unfortunately, I have left without options, as I cannot even delete the damaged archive. This is because the first thing that all operations are trying to do is triggering that 'analyzing' step on each archive, which always crashes when reaching the damaged archive.

**Comment by Ernest0x** [comment]
When trying to delete the damaged archive (with the delete operation) I do not get a traceback, but this:

    Analyzing archive: binlogs_2015-03-09-02:25
    attic: Error: Object with key b'c`e\x959\x12iGF<\xd9\x84=\xc6l\x86\xd9\x08n\r) %\xe2\xf5\xa2\xc5\xa1L\x8c*\x99' not found in repository modcom-db

**Comment by Ernest0x** [comment]
For clarity, I included what is actually printed with the print() calls above:

    item: {b'path': b'var/lib/mysql/binlog.020441', b'gid': 108, b'group': b'mysql', b'mode': 33200, b'mtime': 1425027901071324160}
    StableDict(item): {b'path': b'var/lib/mysql/binlog.020441', b'gid': 108, b'group': b'mysql', b'mode': 33200, b'mtime': 1425027901071324160}
    item: b'uid'

In the code, it seems that robust_iterator() handles only the cases when an archive item is missing (?). However, in my case the item does exist, but has not the correct format: it is a bytestring instead of a dict, which cannot be converted later to a StableDict object, and the traceback occurs. So, would a type check for dict on archive items make the robust_iterator() more, well... robust? I am not sure how that item got packed in the msgpack stream in the first place, but at Ieast, it should be possible to ignore it. Or perhaps, it would be safer to delete the whole archive from the repository. What do you think?

**Comment by ThomasWaldmann** [comment]
the first "item: ..." is a dict, so not causing an error.
the second "item: b'uid'" is just some bytes and can not get converted to a dict. therefore you get a traceback. I'll have a look at the code to find out why that is inconsistent in data type.

**Comment by Ernest0x** [comment]
@ThomasWaldmann your patch did the job. `attic check --repair` did the repairing and `attic delete` deleted the archive. Thanks.

That said, however, I am not sure if the best place to put the check is where you put it in the patch. For example, the `check` operation uses a custom msgpack unpacker class named "RobustUnpacker", which it does try to check for correct format (see the comment: "Abort early if the data does not look like a serialized dict"), but it seems it does not catch my case. The relevant code in 'cache.py', on the other hand, uses msgpack's Unpacker class.
