### ISSUE TITLE
Traceback should be an error informing client why

### ISSUE THREAD

**Issue by duanebc** [jborg/attic#236]
When an encrypted repo is attempted access from a location without the key, the following stack is provided.  I believe a standard error should be given alerting user.

attic list clark1.attic::Initial 
Traceback (most recent call last):
  File "/usr/bin/attic", line 3, in <module>
    main()
  File "/usr/lib64/python3.4/site-packages/attic/archiver.py", line 727, in main
    exit_code = archiver.run(sys.argv[1:])
  File "/usr/lib64/python3.4/site-packages/attic/archiver.py", line 717, in run
    return args.func(args)
  File "/usr/lib64/python3.4/site-packages/attic/archiver.py", line 271, in do_list
    manifest, key = Manifest.load(repository)
  File "/usr/lib64/python3.4/site-packages/attic/helpers.py", line 98, in load
    key = key_factory(repository, cdata)
  File "/usr/lib64/python3.4/site-packages/attic/key.py", line 38, in key_factory
    return KeyfileKey.detect(repository, manifest_data)
  File "/usr/lib64/python3.4/site-packages/attic/key.py", line 205, in detect
    path = cls.find_key_file(repository)
  File "/usr/lib64/python3.4/site-packages/attic/key.py", line 224, in find_key_file
    raise Exception('Key file for repository with ID %s not found' % id)
Exception: Key file for repository with ID e0d0585452b1b10f9f3096c27aeb8c4925f55eeadf57c0da2e0cab56186f94aa not found

CentOS release 6.6 (Final)
Python 3.4.2

Installed via pip

pip3.4 freeze
Attic==0.14
msgpack-python==0.4.6

**Comment by ThomasWaldmann** [comment]
+1
