### ISSUE TITLE
misleading error message when importing fuse support fails

### ISSUE THREAD

**Issue by ThomasWaldmann** [jborg/attic#237]
It says:
```
the "llfuse" module is required to use this feature
```

What really might have happened:
```
Python 3.4.3 (default, Mar 7 2015, 01:46:30)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import llfuse
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/local/Homebrew/lib/python3.4/site-packages/llfuse/__init__.py", line 13, in <module>
from llfuse.capi import *
ImportError: dlopen(/usr/local/Homebrew/lib/python3.4/site-packages/llfuse/capi.so, 2): Library not loaded: /usr/local/lib/libosxfuse.2.dylib
Referenced from: /usr/local/Homebrew/lib/python3.4/site-packages/llfuse/capi.so
Reason: Incompatible library version: capi.so requires version 12.0.0 or later, but libosxfuse.2.dylib provides version 10.0.0
```

You see, llfuse IS there, but the fuse it is based upon is not new enough.
The wrong error msg makes the user wonder why it does not find llfuse though and never sees the real error msg.

**Comment by ThomasWaldmann** [comment]
See PR #238.
