### ISSUE TITLE
BlockingIOError in verbose mode

### ISSUE THREAD

**Issue by Ernest0x** [jborg/attic#26]
With latest attic (commit: 50cabd53b) as well as with previous commits and verbose mode:

    Traceback (most recent call last):
      File "/usr/local/bin/attic", line 5, in <module>
        pkg_resources.run_script('Attic==0.9-6-g50cabd5', 'attic')
      File "/usr/local/lib/python3.3/site-packages/setuptools-2.0-py3.3.egg/pkg_resources.py", line 483, in run_script
      File "/usr/local/lib/python3.3/site-packages/setuptools-2.0-py3.3.egg/pkg_resources.py", line 1341, in run_script
      File "/usr/local/lib/python3.3/site-packages/setuptools-2.0-py3.3.egg/pkg_resources.py", line 50, in execfile
      File "/usr/local/lib/python3.3/site-packages/Attic-0.9_6_g50cabd5-py3.3-linux-x86_64.egg/EGG-INFO/scripts/attic", line 3, in <module>
        main()
      File "/usr/local/lib/python3.3/site-packages/Attic-0.9_6_g50cabd5-py3.3-linux-x86_64.egg/attic/archiver.py", line 479, in main
        exit_code = archiver.run(sys.argv[1:])
      File "/usr/local/lib/python3.3/site-packages/Attic-0.9_6_g50cabd5-py3.3-linux-x86_64.egg/attic/archiver.py", line 473, in run
        return args.func(args)
      File "/usr/local/lib/python3.3/site-packages/Attic-0.9_6_g50cabd5-py3.3-linux-x86_64.egg/attic/archiver.py", line 104, in do_create
        self._process(archive, cache, args.excludes, skip_inodes, path, restrict_dev)
      File "/usr/local/lib/python3.3/site-packages/Attic-0.9_6_g50cabd5-py3.3-linux-x86_64.egg/attic/archiver.py", line 150, in _process
        os.path.join(path, filename), restrict_dev)
      File "/usr/local/lib/python3.3/site-packages/Attic-0.9_6_g50cabd5-py3.3-linux-x86_64.egg/attic/archiver.py", line 150, in _process
        os.path.join(path, filename), restrict_dev)
      File "/usr/local/lib/python3.3/site-packages/Attic-0.9_6_g50cabd5-py3.3-linux-x86_64.egg/attic/archiver.py", line 150, in _process
        os.path.join(path, filename), restrict_dev)
      File "/usr/local/lib/python3.3/site-packages/Attic-0.9_6_g50cabd5-py3.3-linux-x86_64.egg/attic/archiver.py", line 150, in _process
        os.path.join(path, filename), restrict_dev)
      File "/usr/local/lib/python3.3/site-packages/Attic-0.9_6_g50cabd5-py3.3-linux-x86_64.egg/attic/archiver.py", line 150, in _process
        os.path.join(path, filename), restrict_dev)
      File "/usr/local/lib/python3.3/site-packages/Attic-0.9_6_g50cabd5-py3.3-linux-x86_64.egg/attic/archiver.py", line 150, in _process
        os.path.join(path, filename), restrict_dev)
      File "/usr/local/lib/python3.3/site-packages/Attic-0.9_6_g50cabd5-py3.3-linux-x86_64.egg/attic/archiver.py", line 150, in _process
        os.path.join(path, filename), restrict_dev)
      File "/usr/local/lib/python3.3/site-packages/Attic-0.9_6_g50cabd5-py3.3-linux-x86_64.egg/attic/archiver.py", line 150, in _process
        os.path.join(path, filename), restrict_dev)
      File "/usr/local/lib/python3.3/site-packages/Attic-0.9_6_g50cabd5-py3.3-linux-x86_64.egg/attic/archiver.py", line 135, in _process
        self.print_verbose(remove_surrogates(path))
      File "/usr/local/lib/python3.3/site-packages/Attic-0.9_6_g50cabd5-py3.3-linux-x86_64.egg/attic/archiver.py", line 42, in print_verbose
        print(msg)
    BlockingIOError: [Errno 11] write could not complete without blocking
    Exception BlockingIOError: BlockingIOError(11, 'write could not complete without blocking', 0) in <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'> ignored

I had trouble trying to backup around ~330GB/1.5 million files of data to a remote repository, so I enabled verbose mode to see what is happening and I reached to a point that the above error occured.

The remote repository path on the remote host is under an NFS mount on another remote host (NFS server), so the setup can be described like this:  `backup source host --SSH--> remote host --NFS--> repository path`. This setup works without problems with other backup source hosts with far less data (up to 7GB e.g.) sending their backups on the same remote host under the same NFS mount, so I suspect that the bigger size of the source data or maybe the longer time needed to send these may play a role on this.

Any idea what may be causing this?

**Comment by ThomasWaldmann** [comment]
Considering that hashindex does not use mmap any more and this issue is rather old and inactive, should it be closed due to that?

**Comment by Ernest0x** [comment]
> Considering that hashindex does not use mmap any more and this issue is rather old and inactive, should it be closed due to that?

Yes, I think it can be closed.
