### ISSUE TITLE
Attic cannot make backups of files not owned by its user despite having read rights

### ISSUE THREAD

**Issue by UntouchedWagons** [jborg/attic#274]
If a file is made by user X and its permissions is set to 0777, attic cannot backup this file if it is running under user Y:

    cd /media/Scratch
    sudo mkdir test
    sudo echo "Hello" > test/some_file
    sudo chmod 0777 test/some_file
    attic init test-backup.attic
    attic create test-backup.attic::test test
    Traceback (most recent call last):
      File "/usr/local/lib/python3.2/dist-packages/attic/archive.py", line 433, in open_noatime
        fd = os.open(p, flags_noatime)
    OSError: [Errno 1] Operation not permitted: 'test/some_file'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/local/bin/attic", line 3, in <module>
        main()
      File "/usr/local/lib/python3.2/dist-packages/attic/archiver.py", line 727, in main
        exit_code = archiver.run(sys.argv[1:])
      File "/usr/local/lib/python3.2/dist-packages/attic/archiver.py", line 717, in run
        return args.func(args)
      File "/usr/local/lib/python3.2/dist-packages/attic/archiver.py", line 128, in do_create
        self._process(archive, cache, args.excludes, args.exclude_caches, skip_inodes, path, restrict_dev)
      File "/usr/local/lib/python3.2/dist-packages/attic/archiver.py", line 177, in _process
        os.path.join(path, filename), restrict_dev)
      File "/usr/local/lib/python3.2/dist-packages/attic/archiver.py", line 163, in _process
        archive.process_file(path, st, cache)
      File "/usr/local/lib/python3.2/dist-packages/attic/archive.py", line 402, in process_file
        with Archive._open_rb(path, st) as fd:
      File "/usr/local/lib/python3.2/dist-packages/attic/archive.py", line 454, in _open_rb
        return Archive._open_rb(path, st)
      File "/usr/local/lib/python3.2/dist-packages/attic/archive.py", line 434, in open_noatime
        except PermissionError:
    NameError: global name 'PermissionError' is not defined

If I try to read the file via `cat test/some_file` it works just fine. Maybe there's something about python and file permissions I'm not understanding here. The file system mounted at /media/Scratch was mounted using the `noatime` flag so maybe that's causing an issue? I don't know, I don't want to have to make backups as root though.

I'm using attic 0.14 on Debian stable with python 3.2.3.

**Comment by ThomasWaldmann** [comment]
Could you test whether that PR fixes your issue? https://github.com/jborg/attic/pull/244

**Comment by UntouchedWagons** [comment]
Fantastic.

**Comment by UntouchedWagons** [comment]
Yup it works for me.
