### ISSUE TITLE
attic serve is not documented on attic-backup.org

### ISSUE THREAD

**Issue by lfam** [jborg/attic#275]
The --restrict-paths argument to 'attic serve' is a pretty important piece of the program, since it allows you to automate your backups without leave a full-access unencrypted SSH key lying around.

We should really mention it on the website.

**Comment by ThomasWaldmann** [comment]
You could help by writing some docs for it. :)

See there:

https://github.com/jborg/attic/tree/master/docs

**Comment by lfam** [comment]
I wrote something for the "Remote repositories" section of the quickstart. I can submit that as a pull request but I also want there to be documentation in usage.html and I don't understand how to work with usage.rst.

Also 'serve' seems to have some special status based on the following line in archiver.py:
# We can't use argparse for "serve" since we don't want it to show up in Available commands"

**Comment by ThomasWaldmann** [comment]
About working with usage.rst:

```
cd docs/
make html
```
It will then automatically call update_usage.sh and run sphinx on the results.

**Comment by lfam** [comment]
It fails with the following error message:
```
$ make html
./update_usage.sh
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.2.3

Exception occurred:
  File "conf.py", line 14, in <module>
    import sys, os, attic
ImportError: No module named attic
The full traceback has been saved in /tmp/sphinx-err-PXgpe2.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
Makefile:40: recipe for target 'html' failed
make: *** [html] Error 1
```
Here's the traceback:
```
# Sphinx version: 1.2.3
# Python version: 2.7.9
# Docutils version: 0.12 release
# Jinja2 version: 2.7.3
# Loaded extensions:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/cmdline.py", line 253, in main
    warningiserror, tags, verbosity, parallel)
  File "/usr/lib/python2.7/dist-packages/sphinx/application.py", line 107, in __init__
    confoverrides or {}, self.tags)
  File "/usr/lib/python2.7/dist-packages/sphinx/config.py", line 229, in __init__
    execfile_(filename, config)
  File "/usr/lib/python2.7/dist-packages/sphinx/util/pycompat.py", line 105, in execfile_
    exec code in _globals
  File "conf.py", line 14, in <module>
    import sys, os, attic
ImportError: No module named attic
```

**Comment by barsanuphe** [comment]
@lfam I would guess you are getting this because you are using python2.7 and not python3.

**Comment by lfam** [comment]
I have 2.7 and 3 installed in Debian. In Debian, python is a link to
python 2.7 and you have to call python3 if you want python 3.

Do I need to do something to tell the build process to use
/usr/bin/python3 instead of /usr/bin/python?

On Tue, Apr 7, 2015, at 16:18, barsanuphe wrote:
> @lfam[1] I would guess you are getting this because you are using
> python2.7 and not python3.


> — Reply to this email directly or view it on GitHub[2].

>



Links:

  1. https://github.com/lfam
  2. https://github.com/jborg/attic/issues/275#issuecomment-90718376

**Comment by barsanuphe** [comment]
I'm using Arch, which defaults to python3 just as God intended, but I think you probably need to `apt-get install python3-sphinx`.

**Comment by lfam** [comment]
I already have python3-sphinx installed. I have temporarily removed python-sphinx in order to do this work but I think this issue is a bug (in the Makefile?).

However, as I said upthread, I don't know how to properly document the usage of 'serve' because it is ignored by argparse. Is there a reason for this?

**Comment by barsanuphe** [comment]
No, you need to add `serve` in l5 of `update_usage.sh`. Sphinx will generate `usage/serve.rst.inc`. Then you can `.. include:: usage/serve.rst.inc` inside `usage.rst` along with any example you deem suitable.

**Comment by lfam** [comment]
Thank you for the very specific help! I am totally new to sphinx so I really appreciate it.

I've made a pull request with my changes: https://github.com/jborg/attic/pull/277
