### ISSUE TITLE
UnicodeDecodeError on extract

### ISSUE THREAD

**Issue by ghaering** [jborg/attic#289]
This is very bad, because I cannot restore from backups. Shouldn't this occur when archiving the files, too?

```
data/glusterdata/iv-project-data/TestYumpu/fc0fb189-e6f7-4a30-8eaf-4cb87d6c033b/userdata/Blackbase.mp4
data/glusterdata/iv-project-data/TestYumpu/fc0fb189-e6f7-4a30-8eaf-4cb87d6c033b/userdata/The workspace for your life?s work _ Evernote_2014-10-21_12-43-39.png
Traceback (most recent call last):
  File "/root/build/prefix/lib/python3.4/site-packages/cx_Freeze/initscripts/Console.py", line 27, in <module>
  File "prefix/bin/attic", line 3, in <module>
  File "/root/build/prefix/lib/python3.4/site-packages/attic/archiver.py", line 728, in main
  File "/root/build/prefix/lib/python3.4/site-packages/attic/archiver.py", line 718, in run
  File "/root/build/prefix/lib/python3.4/site-packages/attic/archiver.py", line 218, in do_extract
  File "/root/build/prefix/lib/python3.4/site-packages/attic/archive.py", line 246, in extract_item
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 126: ordinal not in range(128)
```

**Comment by ghaering** [comment]
The LANG environment variable was not set. Setting it to en_US.UTF8 fixes the problem.

**Comment by ThomasWaldmann** [comment]
@jborg how about avoiding unpleasant surprises while doing long backup or restore runs by doing a non-ascii test output at the very beginning of an attic run, catch UnicodeError and advise "crash when outputting unicode! set LANG=en_US.UTF-8 [or whatever your console encoding is] to fix this." in the exception handler?

**Comment by jborg** [comment]
> @jborg how about avoiding unpleasant surprises while doing long backup or restore runs by doing a non-ascii test output at the very beginning of an attic run, catch UnicodeError and advise "crash when outputting unicode! set LANG=en_US.UTF-8 [or whatever your console encoding is] to fix this." in the exception handler?

Heh, I was actually already working on a similar fix when I saw your comment.
Unicode filename support in Python 3 is a real mess, platform dependent and hard to get right.
At least now we won't crash with an ugly traceback.
