### ISSUE TITLE
ssh LocalCommand can cause problem with attic 

### ISSUE THREAD

**Issue by jots** [jborg/attic#291]
to help with tmux, have in .ssh/config:
```
Host *
      PermitLocalCommand yes
      LocalCommand if [[ $TERM == screen* ]]; then printf "\033k%n\033\\"; fi                                     
```
I need to remove it to use attic.
It causes attic to die:
```
$ attic init host:/home/repo.attic
Initializing repository at "host:/home/repo.attic"
Traceback (most recent call last):
  File "/usr/local/bin/attic", line 3, in <module>
    main()
  File "/usr/local/lib/python3.4/dist-packages/attic/archiver.py", line 728, in main
    exit_code = archiver.run(sys.argv[1:])
  File "/usr/local/lib/python3.4/dist-packages/attic/archiver.py", line 718, in run
    return args.func(args)
  File "/usr/local/lib/python3.4/dist-packages/attic/archiver.py", line 59, in do_init
    repository = self.open_repository(args.repository, create=True, exclusive=True)
  File "/usr/local/lib/python3.4/dist-packages/attic/archiver.py", line 32, in open_repository
    repository = RemoteRepository(location, create=create)
  File "/usr/local/lib/python3.4/dist-packages/attic/remote.py", line 119, in __init__
    version = self.call('negotiate', 1)
  File "/usr/local/lib/python3.4/dist-packages/attic/remote.py", line 128, in call
    for resp in self.call_many(cmd, [args], **kw):
  File "/usr/local/lib/python3.4/dist-packages/attic/remote.py", line 176, in call_many
    for type, msgid, error, res in self.unpacker:
TypeError: 'int' object is not iterable
````

**Comment by ThomasWaldmann** [comment]
That's strange. Do I understand it correctly? "if terminal is GNU screen, the print the escape sequence otherwise do nothing" - that should not affect attic if you do not run it in screen, right?

**Comment by jots** [comment]
doh!  I was running it in tmux from the command line.  I will remember not to do that in the future.
