### ISSUE TITLE
Error trying to execute "check" on repo

### ISSUE THREAD

**Issue by thiagoc** [jborg/attic#327]
I can "create/list/extract" on this repo, just "check" give the following error:

```
Starting repository check...
hashindex: malloc failed
Traceback (most recent call last):
  File "/usr/bin/attic", line 3, in <module>
    main()
  File "/usr/lib/python3.4/site-packages/attic/archiver.py", line 730, in main
    exit_code = archiver.run(sys.argv[1:])
  File "/usr/lib/python3.4/site-packages/attic/archiver.py", line 720, in run
    return args.func(args)
  File "/usr/lib/python3.4/site-packages/attic/archiver.py", line 81, in do_check
    if repository.check(repair=args.repair):
  File "/usr/lib/python3.4/site-packages/attic/remote.py", line 214, in check
    return self.call('check', repair)
  File "/usr/lib/python3.4/site-packages/attic/remote.py", line 128, in call
    for resp in self.call_many(cmd, [args], **kw):
  File "/usr/lib/python3.4/site-packages/attic/remote.py", line 161, in call_many
    raise self.RPCError(error)
attic.remote.RPCError: b'Exception'
```

Running through SSH with version 0.16 on both.

**Comment by ThomasWaldmann** [comment]
"malloc failed" sounds like you ran out of memory (RAM).
The exception printed after that is pretty useless "as is", because it hides most information.

**Comment by thiagoc** [comment]
How can I get more information? This could be a RAM issue since I store my
repo on a VPS with 512 MB of RAM, but should not attic manage this? Why
only "check" give me this error?

**Comment by ThomasWaldmann** [comment]
With little RAM and lots of data, you might quickly run into misc. memory related issues.
This is because attic keeps infos about chunks and files in memory. I am working on improving this in my fork.

check might be especially big as it opens and processes ALL archives in the repo.

For attic, a workaround might be offering more swap, but it'll get slow then.

**Comment by thiagoc** [comment]
You're right, the problem was that my server was running without Swap at all. Now it works.
