### ISSUE TITLE
TypeError 'int' object is not iterable when doing a third attic create for local repository

### ISSUE THREAD

**Issue by revenant** [jborg/attic#355]
Host is Opensuse 13.2
Python 3.4
Attic 0.16

I've checked https://github.com/jborg/attic/issues/171 and think it is not the same isssue  as msgpack is 0.4.6

This host had some VM client issues prior to this issue but I've run attic check and there were no issues reported.

attic create --stats $REPOSITORY::localhost-`date +%Y%m%d` / --exclude={"/sys","/proc","/dev","/run","/export/backups","/export/install",/mnt}
Traceback (most recent call last):
  File "/usr/bin/attic", line 3, in <module>
    main()
  File "/usr/lib64/python3.4/site-packages/attic/archiver.py", line 730, in main
    exit_code = archiver.run(sys.argv[1:])
  File "/usr/lib64/python3.4/site-packages/attic/archiver.py", line 720, in run
    return args.func(args)
  File "/usr/lib64/python3.4/site-packages/attic/archiver.py", line 129, in do_create
    self._process(archive, cache, args.excludes, args.exclude_caches, skip_inodes, path, restrict_dev)
  File "/usr/lib64/python3.4/site-packages/attic/archiver.py", line 178, in _process
    os.path.join(path, filename), restrict_dev)
  File "/usr/lib64/python3.4/site-packages/attic/archiver.py", line 178, in _process
    os.path.join(path, filename), restrict_dev)
  File "/usr/lib64/python3.4/site-packages/attic/archiver.py", line 164, in _process
    archive.process_file(path, st, cache)
  File "/usr/lib64/python3.4/site-packages/attic/archive.py", line 402, in process_file
    ids = cache.file_known_and_unchanged(path_hash, st)
  File "/usr/lib64/python3.4/site-packages/attic/cache.py", line 259, in file_known_and_unchanged
    self._read_files()
  File "/usr/lib64/python3.4/site-packages/attic/cache.py", line 130, in _read_files
    for path_hash, item in u:
TypeError: 'int' object is not iterable

**Comment by ThomasWaldmann** [comment]
Looks like the cache for that repo is corrupted somehow - can you just delete the cache and retry?

```
cat repo/config  # find out the REPOID
rm -rf ~/.cache/attic/REPOID
```

**Comment by revenant** [comment]
That's fixed it thank you very much.
