### ISSUE TITLE
Unable to find OpenSSL

### ISSUE THREAD

**Issue by obigroup** [jborg/attic#357]
Hello,

When I try to install Attic from pip3 or from pip3 with git:

```
Downloading/unpacking git+https://github.com/jborg/attic
  Cloning https://github.com/jborg/attic to /tmp/pip-i399p2z0-build
  Running setup.py (path:/tmp/pip-i399p2z0-build/setup.py) egg_info for package from git+https://github.com/jborg/attic
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-i399p2z0-build/setup.py", line 74, in <module>
        raise Exception('Unable to find OpenSSL >= 1.0 headers. (Looked here: {})'.format(', '.join(possible_openssl_prefixes)))
    Exception: Unable to find OpenSSL >= 1.0 headers. (Looked here: /usr, /usr/local, /usr/local/opt/openssl, /usr/local/ssl, /usr/local/openssl, /usr/local/attic, /opt/local)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-i399p2z0-build/setup.py", line 74, in <module>

    raise Exception('Unable to find OpenSSL >= 1.0 headers. (Looked here: {})'.format(', '.join(possible_openssl_prefixes)))

Exception: Unable to find OpenSSL >= 1.0 headers. (Looked here: /usr, /usr/local, /usr/local/opt/openssl, /usr/local/ssl, /usr/local/openssl, /usr/local/attic, /opt/local)
```

I am on Debian 8 with virtualenv and wrapper. Openssl is installed.
My aptitude search openssl:

```
i   libgnutls-openssl27                                                                               - bibliothèque GNU TLS - enveloppe OpenSSL                                                                   
v   libopensc-openssl                                                                                 -                                                                                                            
p   libxmlsec1-openssl                                                                                - Openssl engine for the XML security library                                                                
i A openssl                                                                                           - boîte à outils SSL - outils de cryptographie                                                               
p   openssl-blacklist                                                                                 - Blacklists for  OpenSSL RSA keys and tools                                                                 
p   openssl-blacklist-extra                                                                           - Non-default blacklists of OpenSSL RSA keys                                                                 
i   python-openssl                                                                                    - enrobage Python 2 pour la bibliothèque OpenSSL                                                             
p   python-openssl-doc                                                                                - Python wrapper around the OpenSSL library (documentation package)                                          
i   python3-openssl                                                                                   - Python 3 wrapper around the OpenSSL library                
```

Thx for help.

**Comment by ThomasWaldmann** [comment]
apt-get install libssl-dev

**Comment by obigroup** [comment]
@ThomasWaldmann : I tried, it's not resolve my problem.

**Comment by ThomasWaldmann** [comment]
post a new console log if it changed + output of dpkg -l | grep ssl

**Comment by obigroup** [comment]
No change

```
ii  libflac8:amd64                                              1.3.0-3                              amd64        Free Lossless Audio Codec - runtime C library
ii  libgnutls-openssl27:amd64                                   3.3.8-6+deb8u2                       amd64        GNU TLS library - OpenSSL wrapper
ii  libio-socket-ssl-perl                                       2.002-2                              all          Perl module implementing object oriented interface to SSL sockets
ii  libnet-smtp-ssl-perl                                        1.01-3                               all          Perl module providing SSL support to Net::SMTP
ii  libnet-ssleay-perl                                          1.65-1+b1                            amd64        Perl module for Secure Sockets Layer (SSL)
ii  libssl1.0.0:amd64                                           1.0.1k-3+deb8u1                      amd64        Secure Sockets Layer toolkit - shared libraries
ii  libwavpack1:amd64                                           4.70.0-1                             amd64        audio codec (lossy and lossless) - library
ii  openssl                                                     1.0.1k-3+deb8u1                      amd64        Secure Sockets Layer toolkit - cryptographic utility
ii  python-openssl                                              0.14-1                               all          Python 2 wrapper around the OpenSSL library
ii  python3-openssl                                             0.14-1                               all          Python 3 wrapper around the OpenSSL library
ii  ssl-cert                                                    1.0.35                               all          simple debconf wrapper for OpenSSL
```

thx for your reactivity.

**Comment by ThomasWaldmann** [comment]
I don't see libssl-dev there. See my comment above.

**Comment by obigroup** [comment]
Thx, I forgot to reinstall it.

**Comment by Bhavya-Ahir** [comment]
Help me out I am getting same error

C:\Users\bhavya\weblate>pip install -r requirements.txt
Collecting bleach<3.2.0,>=3.1.1
  Downloading bleach-3.1.4-py2.py3-none-any.whl (151 kB)
     |████████████████████████████████| 151 kB 3.3 MB/s
Collecting borgbackup<1.2.0,>=1.1.9
  Downloading borgbackup-1.1.11.tar.gz (3.7 MB)
     |████████████████████████████████| 3.7 MB 84 kB/s
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\bhavya\anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\bhavya\\AppData\\Local\\Temp\\pip-install-cq8smu19\\borgbackup\\setup.py'"'"'; __file__='"'"'C:\\Users\\bhavya\\AppData\\Local\\Temp\\pip-install-cq8smu19\\borgbackup\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\bhavya\AppData\Local\Temp\pip-install-cq8smu19\borgbackup\pip-egg-info'
         cwd: C:\Users\bhavya\AppData\Local\Temp\pip-install-cq8smu19\borgbackup\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\bhavya\AppData\Local\Temp\pip-install-cq8smu19\borgbackup\setup.py", line 188, in <module>
        raise Exception('Unable to find OpenSSL >= 1.0 headers. (Looked here: {})'.format(', '.join(possible_openssl_prefixes)))
    Exception: Unable to find OpenSSL >= 1.0 headers. (Looked here: /usr, /usr/local, /usr/local/opt/openssl, /usr/local/ssl, /usr/local/openssl, /usr/local/borg, /opt/local, /opt/pkg)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

C:\Users\bhavya\weblate>pip install OpenSSL
ERROR: Could not find a version that satisfies the requirement OpenSSL (from versions: none)
ERROR: No matching distribution found for OpenSSL

C:\Users\bhavya\weblate>pip install libssl-dev
ERROR: Could not find a version that satisfies the requirement libssl-dev (from versions: none)
ERROR: No matching distribution found for libssl-dev

system: Windows 10
