### ISSUE TITLE
Cannot mount due to llfuse error

### ISSUE THREAD

**Issue by darkclouder** [jborg/attic#385]
I cannot mount any repository
I used
`attic mount -v -f /path/to/backup.attic::2016-04-16_14:39 backup-mount`
And I'm getting this result:

```
Mounting filesystem
Traceback (most recent call last):
  File "/usr/bin/attic", line 3, in <module>
    main()
  File "/usr/lib/python3.5/site-packages/attic/archiver.py", line 730, in main
    exit_code = archiver.run(sys.argv[1:])
  File "/usr/lib/python3.5/site-packages/attic/archiver.py", line 720, in run
    return args.func(args)
  File "/usr/lib/python3.5/site-packages/attic/archiver.py", line 265, in do_mount
    operations.mount(args.mountpoint, args.options, args.foreground)
  File "/usr/lib/python3.5/site-packages/attic/fuse.py", line 230, in mount
    llfuse.main(single=True)
  File "src/fuse_api.pxi", line 273, in llfuse.main (src/llfuse.c:35175)
TypeError: main() got an unexpected keyword argument 'single'
```

Using Arch Linux with Attic 0.16

**Comment by ThomasWaldmann** [comment]
This is likely because your llfuse is too new (and had api changes meanwhile) and attic was not adapted to it.

**Comment by grizmin** [comment]
File "/usr/lib/python3.5/site-packages/attic/fuse.py", line 230
change to  llfuse.main() and it will work just fine.

**Comment by ikunyemingor** [comment]
This worked for me... based on @ThomasWaldmann suspicion, I located the last llfuse release (v0.41) https://pypi.org/project/llfuse/ after Attic version 0.16 https://github.com/jborg/attic/releases and uninstalled the most recent llfuse I had:
`sudo pip3 uninstall llfuse`
Then installed:
`sudo pip3 install llfuse==0.41`

Hope it helps
